### ISSUE TITLE
JACK Metadata MIDNAM support?

### ISSUE THREAD

**Issue by mxmilkiib** [ahlstromcj/seq66#1]
An implementation of the basic concept of LV2 MIDNAM has been around for a while. More recently there has been discussion on #lad, and, now JACK 2 has metadata implemented, Carla has [started offering](https://github.com/falkTX/Carla/commit/278e1972d89a984a01f6b2618f1063bdfd9e7086) that MIDNAM information as metadata on the midi-in port for a connecting sequencer to use.

**Comment by ahlstromcj** [comment]
So many minor yet annoying internal bugs.  I will consider MIDINAM for version 2.  See the TODO file.
