### ISSUE TITLE
Right click-hold on pattern editor doesn't show draw pencil

### ISSUE THREAD

**Issue by mxmilkiib** [ahlstromcj/seq66#10]

**Comment by ahlstromcj** [comment]
For Qt, the draw icon is a pointing finger. Qt doesn't have a pencil (and I am too lazy to add one).  Also, I added a pointing finger button to the pattern and song editors to make it easier to go into note-insertion and trigger insertion mode, and to show the mode if another way (e.g. right-click or the "p" key) of entering the insertion mode was selected.  This addition was made due a new user's puzzlement over how to insert a note.  Amazing how long some issues take to surface.  Years!

**Comment by mxmilkiib** [comment]
The pointing finger works 👆
