### ISSUE TITLE
Send midi-control-out message when New Pattern is created in GUI

### ISSUE THREAD

**Issue by mathiasfriman** [ahlstromcj/seq66#112]
Hi,

I'm trying to get to grips with seq66, coming from sequencer64 and previously seq24. I just realized that when creating a new pattern with **right click** -> **New pattern**, the new pattern does not show up on my control surface upon creation. The new pattern is outlined in red.

![create-new-pattern-midi-control-out](https://github.com/ahlstromcj/seq66/assets/3397596/787234c7-43f5-4a6c-9c24-7ecd210ac5eb)

However, as previously stated, the control surface does not show the newly created pattern.

![control-surface-pre-arming](https://github.com/ahlstromcj/seq66/assets/3397596/cb4dc4b8-857d-4aa0-90d8-84b5f80d0d74)

Until I press the button for the pattern itself (EDIT: or arm/queue it by pressing **w** on the keyboard). Seq66 then sends **Arm** or **Queue** midi signals to the control surface, depending on if the keep-queue function is set (**Q** in the interface).

![control-surface-after-pressing-button](https://github.com/ahlstromcj/seq66/assets/3397596/de81f26b-9cf9-492e-a651-65794f2bdac7)

Could it be done that if a control surface is defined, to send a midi-control-out message to the specified pattern slot as setup in qseq66.ctrl when a pattern is created?

**Comment by ahlstromcj** [comment]
Hmmm, that's supposed to work.  Will look into it in the next few days.

**Comment by ahlstromcj** [comment]
Just found that I neglect to add an announce_sequence() call the performer::new_sequence().  Will test later today.  Doh!

**Comment by mathiasfriman** [comment]
This works for me now! Thank you so much. :)
