### ISSUE TITLE
Create New Pattern from midi control surface?

### ISSUE THREAD

**Issue by mathiasfriman** [ahlstromcj/seq66#113]
Hi, it's me again.

I would like to be able to create a new pattern (like with **right click -> New pattern** in the UI), but directly from pushing some buttons on my Launchpad Pro (the oldest version). I've tried to scour the manual and these issues for ways to do it, but no luck yet. 

Is there a non-obvious way to do this that I am yet to discover?

The Launchpad Pro mk I has the following layout in Programmer-mode. The square buttons sends regular MIDI On/Off messages, and the round ones send MIDI CC messages.

![LaunchpadPro-prgm-layout](https://github.com/ahlstromcj/seq66/assets/3397596/c2328cd5-bcd7-4112-8ede-69b0083d3707)

My idea was that maybe one could hold one of the CC buttons down while pressing on one of the square slots, or just toggle a "create new pattern" CC button while creating new patterns, then untoggle when done. 

Is that something that is possible, or does it need a complete overhaul of some intricate function?

**Comment by ahlstromcj** [comment]
In the 'ctrl' file, the "=" key / "Loop Edit" line should open up
a new pattern editor window. See the data/linux/qseq66-lp-mini-alt.ctrl
file for an example.

I will double check tomorrow with my Launchpad Mini to see what's up. I assume
all you want is it to open a window for you to create a new pattern via the
mouse or via recording.  Let me know if I am misguided.  Thank you!

**Comment by mathiasfriman** [comment]
Yes, pressing a pad/button on the Launchpad Pro and then pressing '**=**' on the keyboard seem to do the trick. I updated my .ctrl file and it worked like a charm. I even got right into the new pattern, liked it a lot! This was even better than I hoped for! :) Super helpful!
