### ISSUE TITLE
[feature request] Include keyboard shortcut in setToolTip function?

### ISSUE THREAD

**Issue by mathiasfriman** [ahlstromcj/seq66#114]
Is it possible to modify the setToolTip function so that it includes the keyboard shortcut in the onMouseOver (in lack of a better term) toolTip?

Like for Loop Mode, instead of `Cycles through the recording styles.` it could say something like `Cycles through the recording styles. - KP_*`

I feel it would help new users come to grips with the software a lot quicker. The true power of this sequencer is unleashed when you got all shortcuts in muscle memory. There are so many controls and it is hard to keep track of them all. There are also some that are similarly named in the .ctrl file, and this could clear up some misunderstandings. At least it would help yours truly a whole lot. :)

**Comment by ahlstromcj** [comment]
Sounds like a good idea! Will take some time to fully implement.

**Comment by ahlstromcj** [comment]
I'm calling this done.  In addition to tooltips that match the current configuration, added access to installed HTML tables that list the hard-wired keystrokes in the pattern editor and song editor "piano rolls".  Can re-open if anything more needs to be added.
