### ISSUE TITLE
Note rendering problem

### ISSUE THREAD

**Issue by mxmilkiib** [ahlstromcj/seq66#12]
Having a long note, scrolling it out of vision and back again leads to a problem;

![image](https://user-images.githubusercontent.com/108225/87544548-8bc07600-c69e-11ea-8de0-f5ebdb373b5e.png)

**Comment by ahlstromcj** [comment]
So far I haven't been about to duplicate the long-note rendering problem.  Let me know if you still can duplicate it (if you have time!)

**Comment by ahlstromcj** [comment]
Going to close this one.  If it recurs, please open a new issue with a more recent version of Seq66.
