### ISSUE TITLE
compilation error

### ISSUE THREAD

**Issue by michal-cab** [ahlstromcj/seq66#120]
hello, i am on ubunstudio 22.04 and after ./configure seq66 compilation ends with following error:

libtool: link: g++ -I../libseq66/include -I../libsessions/include -I../seq_rtmidi/include -I../seq_qt5/include -pipe -O2 -Wall -W -D_REENTRANT -fPIC -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I. -I/home/tao/anaconda3/include/qt -I/home/tao/anaconda3/include/qt/QtWidgets -I/home/tao/anaconda3/include/qt/QtGui -I/home/tao/anaconda3/include/qt/QtCore -I. -I/home/tao/anaconda3/mkspecs/linux-g++ -I ../libsessions/include -g -O2 -Wall -Wextra -pedantic -Wno-parentheses -D_REENTRANT -DAPI_VERSION=0.99 -std=gnu++1y -pipe -Wno-variadic-macros -Wno-deprecated-declarations -Wl,--copy-dt-needed-entries -o .libs/qseq66 seq66qt5.o  -L../libsessions/src/.libs/ -L/home/tao/source/seq66/seq_qt5/src/.libs /home/tao/source/seq66/seq_qt5/src/.libs/libseq_qt5.so -L/home/tao/source/seq66/libsessions/src/.libs -L/home/tao/source/seq66/libseq66/src/.libs /home/tao/source/seq66/libseq66/src/.libs/libseq66.so /home/tao/source/seq66/libsessions/src/.libs/libsessions.so -L/home/tao/source/seq66/seq_rtmidi/src/.libs /home/tao/source/seq66/seq_rtmidi/src/.libs/libseq_rtmidi.so -llo -L/home/tao/anaconda3/lib /home/tao/anaconda3/lib/libQt5Widgets.so /home/tao/anaconda3/lib/libQt5Gui.so /home/tao/anaconda3/lib/libQt5Core.so -lGL -ljack -lasound -lm -lpthread -Wl,-rpath -Wl,/usr/local/lib/seq66-0.99 -Wl,-rpath -Wl,/home/tao/anaconda3/lib
/usr/bin/ld: /home/tao/source/seq66/libseq66/src/.libs/libseq66.so: undefined reference to `std::condition_variable::wait(std::unique_lock<std::mutex>&)@GLIBCXX_3.4.30'
/usr/bin/ld: /home/tao/source/seq66/seq_qt5/src/.libs/libseq_qt5.so: undefined reference to `std::__throw_bad_array_new_length()@GLIBCXX_3.4.29'
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:641: qseq66] Error 1

**Comment by ahlstromcj** [comment]
Sorry to be so late, was distracted. Not yet sure what to make of the above. The C++ should be C++11 or above. I would imagine Ubuntu Studio's install satisfies that. My older version of Ubuntu uses g++ v. 9.4 = C++ 201402.  Let me know if you figure this out, I got some goo-goo'ling to do.
