### ISSUE TITLE
LICENSE file?

### ISSUE THREAD

**Issue by luzpaz** [ahlstromcj/seq66#122]
Is there one?  
If so, would it be possible to be in a more prominent place (top level directory) ? 

TIA

**Comment by ahlstromcj** [comment]
I can do that.  Do you have any special format you need? Is the current format (in file data/license.text) fine? Do you want it with markup? Thanks again!

**Comment by luzpaz** [comment]
nothing special. just a good old fashioned LICENSE file.

**Comment by mxmilkiib** [comment]
Note that wget has a standard GPL-3.0 license file, and thusly the sidebar on the main GitHub (mirror) page reflects this: https://github.com/mirror/wget

Curl has the Curl License, though this is still an [SPDX registered](https://spdx.org/licenses/curl.html) licence, so the sidebar states a generic link text: https://github.com/curl/curl

Mixxx has an ambiguous situation, having _both_ a non-standard LICENSE and a COPYING,m so gets the sidebar text "Unknown, Unknown licenses found".

license.text is non-standard, in that it combines two licenses. I'm not sure what the best practice is here; maybe it is a case of the main license in the root directory, and the library license in the library directory or such, with an all encompasing notice in the README.

Canonical licence texts can be easily aquired via [SPDX](https://spdx.org/licenses/).
 
GitHub uses [licensee](https://github.com/licensee/licensee) to detect the licence.

**Comment by ahlstromcj** [comment]
For now, I just downloaded gpl.txt, stored it as GPL.txt, and made a reference to it in the LICENSE file.  Similar for lgpl.txt and fdl.txt.

Can refine this in a later revision.

I noticed the wget license link is to a file called COPYING.
