### ISSUE TITLE
Would it be possible to have NEWS structured like a changelog

### ISSUE THREAD

**Issue by luzpaz** [ahlstromcj/seq66#123]
For easier downstream parsing

https://keepachangelog.com/en/1.1.0/

**Comment by ahlstromcj** [comment]
I see that, sounds like a good idea. But can you point me to an actual changelog so I can see a full-fledged example? Thanks!

**Comment by ahlstromcj** [comment]
Heh, I didn't see the vertical scroll bar at that site. So no action needed.

**Comment by ahlstromcj** [comment]
Check out the new NEWS and render any feedback you want. Thanks!

**Comment by luzpaz** [comment]
Looks great! Thanks!
