### ISSUE TITLE
Probelm with 'Program Change'

### ISSUE THREAD

**Issue by Dixi385** [ahlstromcj/seq66#127]
Hey, i'm using **Seq66-0.99.12 Windows** version and i'm trying to setting **'Program Change'** because i want to change voices of my Yamaha midi keyboard but when i press CTRL and i move the cursor nothing happens (i don't see any vertical line, circles or numbers), why? The only **'Event'** parameter that works is **'Tempo'**.

**Comment by ahlstromcj** [comment]
Is this in the Event pane (the thin panel below the pattern editor piano
roll, and moving the mouse in the Data pane? That's supposed to work. If I
don't hear from you I will try to duplicate. Thanks!


Chris Ahlstrom

**Comment by Dixi385** [comment]
https://github.com/ahlstromcj/seq66/assets/145459016/a5cb6352-d635-434a-b53f-479ba57d3316

am i wrong something?

**Comment by Dixi385** [comment]
Hey, i finally solved the problem! I had to right click on a scene and choose **'edit events in tab'** and add a program change with the number of the voice that wanted to use. Thanks, for your previous reply!

**Comment by ahlstromcj** [comment]
There is another way to add events (besides adding notes):

     In the Pattern Editor window:

         1. Click the "Event" button and select the desired event
            (e.g. "Program Change" or "Control 7 Volume").

         2. Click on the Event pane (the thin grey pane below the piano
            roll grid).

         3. Hit the "i" (insert) or "p" (paint) key. A pointing finger
            mouse cursor should appear.

         4. Drag the mouse rightward to created events (little rectangles).

         5. Hit the "Esc" key or "x" (eXit) key to leave insert mode.
            The mouse cursor will appear normal.

         6. In the Data pane at the bottom, click and drag to change
            the values of the events.

Obviously, this works better for continuous data like volume rather than
discrete data like Program Change.

I need to beef up section 6.5 of the user manual to better explain this
process.

Thanks for your input!
