### ISSUE TITLE
Recording type for loop button not working

### ISSUE THREAD

**Issue by thoth-amon** [ahlstromcj/seq66#128]
Tested with version 0.99.13

The button on the main page for recording styles Overdub, Overwrite, Expand and One Shot does not change the property of the pattern. The drop down menu in the pattern window works fine, although Overdub is called Merge here, which is not ideal.

**Comment by ahlstromcj** [comment]
Thanks for the report. I will work on it soon.

**Comment by thoth-amon** [comment]
Tested with the latest release. The buttons on the main page now work.

One shot still behaves like overdub. I am presuming it's meant to turn off the record arming after the first loop?

**Comment by ahlstromcj** [comment]
> One shot still behaves like overdub. I am presuming it's meant to turn off
> the record arming after the first loop?

The second part is correct; I use that to record one measure of a pattern from
an old drum machine. I will look into the first part to see if it is a bug or a
feature. Thanks!

**Comment by thoth-amon** [comment]
I checked the manual and the text for this feature is 

>  Oneshot.
> 
>  When this option is set, with the record button on, and no pattern playing,
> recording won't start until a note comes in, and when the first note comes in, the progress
> bar starts at the left (time 0). As each new set of notes at the same timestamp come in, the
> notes are recorded and the current time advances by one snap value. The length of each note
> is determined by the snap size for the spacing of drawn events. At the end of the pattern,
> recording stops automatically. 
> 
> Remember that Oneshot playback is a kind of auto-step/step-edit recording, and that auto-step/step-
> edit can also be done by click-dragging the mouse. Do not confuse it with Oneshot playback.

So, it's not quite as I thought. I tested it using step input and it is a bit hit and miss whether it turns off the record arm at the end of the loop. Mostly miss and it just overdubs. It also sometimes turns the record arm off instantly.

This may or may not be related to a separate problem(s) I have found with step input where it doesn't loop properly on any mode. Step input seems to read the loop as one more  step than it actually is. So on overdub the extra step will appear at the beginning of the loop and the subsequent loop's second step will appear over the a step behind. On overwrite, it won't overwrite till the second step of the loop and again the step will one behind. Expand overdubs rather than expands on step input.

That all said, it would nice to also have the option to record one loop and then it cut the record arm automatically as I thought one shot was meant to do.

**Comment by ahlstromcj** [comment]
Thanks for the report! I will look into it all soon. I'm glad you've dug a
little deeper.

**Comment by ahlstromcj** [comment]
Had to do some NSM fixes, now your bug is the next priority.

**Comment by ahlstromcj** [comment]
I have found many issues along the way, and also refactored some things.
Getting close to having decent pattern-expand while playback is going.
The expansion issue seems to have occurred after version 0.99.2!

Also, whereas expansion would occur only when a note was struck, I'm
feeling that it should occur all the time, otherwise there's no immediate
feedback when a note is finally struck.

I still have to improve the pattern updates under expansion. Once I do that, I
will see what can be done with auto-step and with step-edit (with the mouse).

It's been a lot rougher ride than I had hoped.  Check out the "wip" branch if
you want to. I've been keeping the NEW and RELNOTES files up-to-date.

**Comment by thoth-amon** [comment]
I've been testing the WIP branch. I am getting an issue with the expand when recording live midi into it. When it gets to the ninth bar, it wipes all the midi recorded before it except the first bar.  The same then happens at bars,16, 17 and 24. Always all bars before except the first. I didn't go longer than that but you get the idea. With step entry,  there is a pop up which warns that events will be dropped when you reach those bars.

Separately, The looping with step entry is better now.

**Comment by ahlstromcj** [comment]
I had not observed that when I was testing awhile ago. But perhaps I broke something in the meantime. I'm tying up some other loose ends now, then I will test and fix again. Thanks for reporting! Your issue made me find a lot of other problems.

**Comment by ahlstromcj** [comment]
As I figured, I made that bug that erased notes. I forget to enable part of the
expand-recording support in the sequence class.  Checked into wip.

I still have a few more things to clean up before making a release. One thing
is the note paint for rapid input of the same note via MIDI. Probably another
CA-special bug :-(.

-- 
economist, n:
	Someone who's good with figures, but doesn't have enough
	personality to become an accountant.

**Comment by thoth-amon** [comment]
Thank you, I'll mark it as closed as the fix has made it into a release. I think there is one new side effect I found but I'll put in a separate report for easier admin.

**Comment by ahlstromcj** [comment]
Thanks! I did find an issue with linking notes (so they can be displayed
properly) and an issue with some notes being quantized to zero lengths. These
issues are currently fixed in the "wip" branch.  Bugs are never ending, sigh.

-- 
"Rembrandt's first name was Beauregard, which is why he never used it."
		-- Dave Barry
