### ISSUE TITLE
Quantized Record Button problem

### ISSUE THREAD

**Issue by thoth-amon** [ahlstromcj/seq66#129]
Tested with 0.99.13 on mx linux

There is a button in the pattern window to turn on Quantized Record.  If the Record Active button to the left of it is set to on then this button does not work. If the Record Active button is off then the Quantized Record button turns on both buttons without issue.

**Comment by ahlstromcj** [comment]
Thanks you again for reporting an issue!

**Comment by thoth-amon** [comment]
I tested with the latest release and can confirm it's fixed. Thanks
