### ISSUE TITLE
Build issue in Linux 

### ISSUE THREAD

**Issue by tank-trax** [ahlstromcj/seq66#14]
Using Debian Buster

after running 

```
libtoolize
automake --add-missing
./configure --enable-release --enable-rtmidi
```
had this error
```
configure: creating ./config.status
config.status: error: cannot find input file: `Makefile.in'
```

resolved by the following...

```
aclocal
autoconf
libtoolize
automake --add-missing
./configure --enable-release --enable-rtmidi
```

**Comment by ahlstromcj** [comment]
The bootstrap script takes care of all that.  Run

    ./bootstrap --full-clean    # to guarantee all chaff is gone
    ./bootstrap -er             # --enable-release

and it will also configure for release as well.  There are more options:

    ./bootstrap --help

Good luck, let me know how it goes. Also check out the INSTALL file, which notes
a lot of potential issues to watch for that have been encountered over the years.
There's some new code in the "optimizing" branch.  

-------- tank-trax 13:11 Wed 22 Jul      --------

>Using Debian Buster
>
>after running
>
>```
>libtoolize
>automake --add-missing
>./configure --enable-release --enable-rtmidi
>```
>had this error
>```
>configure: creating ./config.status
>config.status: error: cannot find input file: `Makefile.in'
>```
>
>resolved by the following...
>
>```
>aclocal
>autoconf
>libtoolize
>automake --add-missing
>./configure --enable-release --enable-rtmidi
>```
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/ahlstromcj/seq66/issues/14

-- 
A candidate is a person who gets money from the rich and votes from the
poor to protect them from each other.

**Comment by muranyia** [comment]
The "Quick Install" section of `INSTALL` might need to be updated to include the instruction to run the `bootstrap` script.

**Comment by ahlstromcj** [comment]
The bootstrap script will do all that. including configuring.

$ ./bootstrap --full-clean
$ ./bootstrap -er
$ make
$ sudo make install

**Comment by ahlstromcj** [comment]
I've also added fix for the normal "./configure; make; make install" mantra.  See the master branch version 0.91.1.  Let me know if there are still build issues, had to fix some other reported issues with that mantra.

**Comment by ahlstromcj** [comment]
Found that I needed to add some Makefile.in files to Git and make sure that cleaning does not remove them.  Also added a "make-checkout" script so that I don't check-in Makefile.ins just because I built on a different machine.
