### ISSUE TITLE
Crash when closing Set Window

### ISSUE THREAD

**Issue by datenbrei** [ahlstromcj/seq66#15]
OS: Manjaro-Linux 5.7.9-1-MANJARO x86_64
Version: seq66-git 0.90.3.r181.70e9302-1 (master)

When opening the "Set" window and not closing it with the close button, but from the window manager's upper right close button, the program crashes.

**Comment by ahlstromcj** [comment]
Can you post a screenshot of the window you are talking about?  I don't see a Close button and am not able to figure out what you are looking at.  Thanks!

**Comment by wongit** [comment]
I think it's the "Set Master" window. I get the same crash on master compile qseq66. Have title bars disabled here so I'm killing/closing with my window manager.

**Comment by ahlstromcj** [comment]
Is this still an issue (in master 0.91.1)?  Let me know.  And thanks for your reports!

**Comment by ahlstromcj** [comment]
There are some other issues with the external set master, so I have macroed it out.  The setmaster tab seems sufficient at this time.  Closing this issue.  If you REALLY need the external set master, let me know.
