### ISSUE TITLE
Ableton Link transport support?

### ISSUE THREAD

**Issue by mxmilkiib** [ahlstromcj/seq66#16]
JACK Transport has [limitations](https://github.com/jackaudio/jackaudio.github.com/wiki/JACK-Transport-limitations), but there is related (arguably more widely used, though not by FOSS) system available; [Ableton Link](https://github.com/Ableton/link). There is also [Carabiner](https://github.com/Deep-Symmetry/carabiner) and its related tools that can provide sync with Pioneer DJ equipment and other software such as [Orac](https://llllllll.co/t/orca-livecoding-tool/17689).

**Comment by grammoboy2** [comment]
In theory, every application that supports JACK Transport, supports Ableton Link via JACK Link
https://github.com/rncbc/jack_link

**Comment by ahlstromcj** [comment]
I will think about this, busy as heck right now with day work and getting non-session-manager support working.  I am a little worried in that a little research shows not many open-source projects working on this.  Stay tuned, and provide extra input.  Thanks guys!

**Comment by mxmilkiib** [comment]
@ahlstromcj I'm incredibly appreciative of all your work towards NSM support, thank you :)

The specific reason part of why I made the request is because of [this](https://linuxmusicians.com/viewtopic.php?f=48&t=21896) LM.com thread (ctrl-f "seq")

The general reason part of the request is because Link has become *the* method of syncing audio apps together. Support for it in the FOSS audio scene is indeed incredibly limited currently (Carla is the only one I know of so far, aside from Carabiner), but my educated guess is that if seq66 supported Link then seq66 would then become highly interesting to people in the (larger) commercial audio software scene that does use Link.

Ableton Link is much newer than JACK Transport, but already [many more apps](https://www.ableton.com/en/link/products/) support it.

And while I'm on the topic, [here's](https://www.ableton.com/en/manual/link-synchronization-and-rewire/) the Ableton Live manual section for Link.

**Comment by falkTX** [comment]
This might be useful https://github.com/falkTX/Hylia/blob/master/hylia.h

Used by carla and mod-host. I need to announce this project still, and make a proper release, but basically my idea was to "dumb down" the link stuff to a super simple C API, which is easier to understand than the official C++ templated classes.
Plus also making it easier to build, just needs a "make"

**Comment by grammoboy2** [comment]
@mxmilkiib You seems to imply that Ableton Link is something new that should replace Jack Transport. They're different. They've different goals. And that educated guess... let's keep being realistic here... 
Carla, Supercollider (and Tidal Cycles) and Ardour has Link support (Ardour is not really suitable for it according to it's main dev, as it doesn't save stuff in memory but on disk, not sure how this is true or not for seq66). But afaik, with Jack Link, every application does have **in theory** support for it, at least that was what P. Davis told me.

**Comment by grammoboy2** [comment]
With Ableton Link you might be able to create some kind of modular 'Ableton/Bitwig-workflow', for recording midi/audio patterns and play them in the same beat. Seq66, Luppp, Non-Mixer, Carla, ... could be part of such a workflow. In that sense you could argue that Ableton Link could be especially useful on the Linux platform.

**Comment by grammoboy2** [comment]
Qmidiarp synced with Supercollider via jack_link seems to work.
https://github.com/rncbc/jack_link

**Comment by grammoboy2** [comment]
See https://github.com/ahlstromcj/seq66/issues/34

**Comment by grammoboy2** [comment]
FYI: Patroneo pattern sequencer works too

**Comment by ahlstromcj** [comment]
Gotta big backlog alluvasudden. Will get to it eventually. Too bad I gotta
work all day on work stuff! 😄

**Comment by grammoboy2** [comment]
Here more noise ;)
Short howto FYI
https://linuxmusicians.com/viewtopic.php?f=19&t=22430

**Comment by ahlstromcj** [comment]
Gonna push this consideration off to version 2.  Let it fester/mature/metastisize/whatever. I want to refactor a metric assload of stuff for version 2. Everything from configuration/undo/redo to adaptive support for plugging/unplugging devices.  My brain hurts :-D.

**Comment by mxmilkiib** [comment]
of interest; https://github.com/mixxxdj/mixxx/pull/10999
