### ISSUE TITLE
Connect midi devices by name

### ISSUE THREAD

**Issue by wvengen** [ahlstromcj/seq66#17]
Currently midi devices are mapped by bus number. This is a problem when devices are added and removed, which happens a lot for me. Why not storing and connecting midi devices by name instead?

This could even be backwards-compatible: when the configuration file has a bus number, use that, if it is a string, connect by name.

**Comment by ahlstromcj** [comment]
I think this is a great idea.  The way it is done now is from seq24; not bad, but yeah, could be improved.  I will think about this issue.  It will be a little while because I am tied up with the "nsm" (non-session-manager) branch.

**Comment by ahlstromcj** [comment]
I thought better of this.  A track/pattern in a song has a buss number.  It can be transported to another user's system and the buss number can be mapped to the desired device using the portmap feature. This associates a buss number with a device by name. If the device name were stored in the pattern, the song would no longer be portable.
