### ISSUE TITLE
Mute Group does not toggle

### ISSUE THREAD

**Issue by miguelhp89** [ahlstromcj/seq66#18]
Not sure if I have missed some configuration but I have the following problem:

I have configured into the .ctrl file the following in order to toggle the first mute group using a midi controller. It send a Control Change message (176 decimal or 0xb0 hex) with the CC number 27. When I press the pad 27 on my midi controller it unmute all the patterns configured in the first mute group but when I press the pad one more time it does not mute the patterns. I have configured the mute group using the mute group tab and include all patterns of the first row.

Also I have noticed that when I activate a mute group I'm not able to activate patters that don't belong to the activated mute group. It is normal?

My objetive is to emulate the "scene" function that some sequencers have (like Ableton Live). That function activate / unactivate an entire row just using one single button. So, if there is another way to emulate let me know it please.

![Captura de pantalla de 2020-09-19 15-57-50](https://user-images.githubusercontent.com/64214167/93669021-31260a80-fa91-11ea-8ee5-c530abc3402b.png)
![Captura de pantalla de 2020-09-19 15-59-19](https://user-images.githubusercontent.com/64214167/93669027-397e4580-fa91-11ea-86d9-426461ad6b82.png)

**Comment by ahlstromcj** [comment]
I believe I made some mistake here.  Will look at it when I have some time, maybe not until the weekend.  Thanks!

**Comment by miguelhp89** [comment]
> I believe I made some mistake here. Will look at it when I have some time, maybe not until the weekend. Thanks!

Let me know if you need more information!

**Comment by ahlstromcj** [comment]
This should be fixed now in the master 0.91.1.  Let me know of any remaining issues.  Thanks!
