### ISSUE TITLE
JackClient::Execute error name = seq66_transport

### ISSUE THREAD

**Issue by mathiasfriman** [ahlstromcj/seq66#20]
Hi gang!

I have a sequencer64 install that works great, but I'm taking a shot at getting Seq66 working. The biggest problem now is that the Jack client registration seems to not work. It registers the ports in QJackCtl, however I cannot connect anything to the MIDI outputs, QJackCtl reports that 

    ERROR: Cannot connect ports owned by inactive clients: "seq66" is not active

and when starting `./qseq66 -t -v` I get

    SuspendRefNum error
    JackClient::Execute error name = seq66_transport
    [[JACK shutdown. JACK sync disabled.]]

As I said, when launching sequencer64 it works just fine, so there seems to be something wrong with this checkout. Cloned the repo an hour ago and built according to instructions in INSTALL.

**Comment by ahlstromcj** [comment]
Not sure what's up.  After starting qjackctl, I can run yoshimi and
seq64/qseq66 and see that the MIDI connections are made, no errors, but I don't
get any action from yoshimi.  Once I can get seq64 running and playing, I will
then tackle seq66.  I haven't messed with the JACK end in quite awhile, as far
as I know (git log might prove me wrong, yeah, I touched something August 12).

-------- mathiasfriman 14:16 Mon 05 Oct      --------

>Hi gang!
>
>I have a sequencer64 install that works great, but I'm taking a shot at getting Seq66 working. The biggest problem now is that the Jack client registration seems to not work. It registers the ports in QJackCtl, however I cannot connect anything to the MIDI outputs, QJackCtl reports that
>
>    ERROR: Cannot connect ports owned by inactive clients: "seq66" is not active
>
>and when starting `./qseq66 -t -v` I get
>
>    SuspendRefNum error
>    JackClient::Execute error name = seq66_transport
>    [[JACK shutdown. JACK sync disabled.]]
>
>As I said, when launching sequencer64 it works just fine, so there seems to be something wrong with this checkout. Cloned the repo an hour ago and built according to instructions in INSTALL.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/ahlstromcj/seq66/issues/20

-- 
"Pay no attention to the man behind the curtain."
		-- Karl, as he stepped behind the computer to reboot it, during a FAT

**Comment by mathiasfriman** [comment]
Tried to revert to commit 124e8241904ca7d6b15ccada922d4382d81e90cc from May, same problem. I'll go backwards and see if I get it working with older commits somehow.

**Comment by ahlstromcj** [comment]
Still not able to duplicate it.  I stop the mpd (which is use for listening to music), start qjackctl, start either Yoshimi or QSynth, start qseq66 in JACK MIDI mode.  Then I can make reconnections from qseq66 outputs to the synth inputs, with no error messages, and play the tune.  What version of Linux are you using?    Anyway, if you do find a commit boundary where it works for you, then doesn't work, go ahead and post the two commits here.  I assume you are working off the master branch.  I also built off the nsm branch and that works, too.  Thanx!

**Comment by mathiasfriman** [comment]
Must be something with this specific computer, I compiled it just fine on an Ubuntu Studio 20.04 and that worked. This is an old install of ElementaryOS with lots of weird things happening in it. Closing this issue. Thank you for trying, will continue to test seq66 now. :)

**Comment by mathiasfriman** [comment]
PS. Really sorry for wasting your time with this wild goose chase. Thank you for all the work you are putting into this awesome project. DS.

**Comment by ahlstromcj** [comment]
No problem.  It was good to go through some scenarios using qjackctl and verify
that I didn't break anything obvious.  Plus, it looks like qjackctl is steadily
adding features!

Have fun!  Trying to document seq66 now, will take awhile, keeping finding issues
when I try to document things.

-------- mathiasfriman 20:27 Thu 08 Oct      --------

>PS. Really sorry for wasting your time with this wild goose chase. Thank you for all the work you are putting into this awesome project. DS.
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/ahlstromcj/seq66/issues/20#issuecomment-705946243

-- 
Woman was taken out of man -- not out of his head, to rule over him; nor
out of his feet, to be trampled under by him; but out of his side, to be
equal to him -- under his arm, that he might protect her, and near his heart
that he might love her.
		-- Henry
