### ISSUE TITLE
Wrong links in about dialog

### ISSUE THREAD

**Issue by datenbrei** [ahlstromcj/seq66#21]
In the file seq_qt5/forms/qsabout.ui in line 61 and 100 there is a wrong link location. When right clicking on the first link (copy link location) you get an email address from a guy called oli.
This needs to be changed, it may be a relict from somewhen.
Also it would be fine if you could directly click on the link with the left mouse button, as usual.

**Comment by ahlstromcj** [comment]
This fix should be in master by now.  Let me know of any remaining issues!
