### ISSUE TITLE
Arch Linux PKGBUILD file for seq66

### ISSUE THREAD

**Issue by datenbrei** [ahlstromcj/seq66#22]
I adapted a script from Christopher Arndt for to build seq66 on Arch Linux as a package. Since I'm not a package maintainer I just provide it here, so that it may be included in the build/install documentation or maybe an already active AUR package maintainer would like to take it and make it it "official". ;-)

~~~
# Adapted from a script of Christopher Arndt <aur -at- chrisarndt -dot- de>

_pkgname=seq66
pkgname="${_pkgname}-git"
pkgver=0.90.6.r230.2a73c11
pkgrel=1
pkgdesc="A live-looping sequencer with an Qt graphical interface (git version)"
arch=('i686' 'x86_64')
url="https://github.com/ahlstromcj/seq66"
license=('GPL2')
depends=('alsa-lib' 'jack' 'qt5-base')
makedepends=('git')
groups=('pro-audio')
provides=("${_pkgname}" "${_pkgname}=${pkgver//.r*/}")
conflicts=("${_pkgname}")
source=("${_pkgname}::git+https://github.com/ahlstromcj/${_pkgname}.git")
md5sums=('SKIP')

pkgver() {
  cd "${srcdir}/${_pkgname}"
  echo "$(git describe).r$(git rev-list --count HEAD).$(git rev-parse --short HEAD)"
}

build() {
  cd "${srcdir}/${_pkgname}"
  ./bootstrap
  ./configure --prefix=/usr --enable-rtmidi
  make
}

package() {
  cd "${srcdir}/${_pkgname}"
  make DESTDIR="${pkgdir}/" install
}
~~~

**Comment by ahlstromcj** [comment]
I've added to the seq66/arch/package directory as PKGBUILD-alt.  Compare it to
the version from Daniel Appelt and let me know your thoughts.  Thanks!

-------- Martin Döring 08:35 Wed 28 Oct      --------

>I adapted a script from Christopher Arndt for to build seq66 on Arch Linux as a package. Since I'm not a package maintainer I just provide it here, so that it may be included in the build/install documentation or maybe an already active AUR package maintainer would like to take it and make it it "official". ;-)
>
>~~~
># Adapted from a script of Christopher Arndt <aur -at- chrisarndt -dot- de>
>
>_pkgname=seq66
>pkgname="${_pkgname}-git"
>pkgver=0.90.6.r230.2a73c11
>pkgrel=1
>pkgdesc="A live-looping sequencer with an Qt graphical interface (git version)"
>arch=('i686' 'x86_64')
>url="https://github.com/ahlstromcj/seq66"
>license=('GPL2')
>depends=('alsa-lib' 'jack' 'qt5-base')
>makedepends=('git')
>groups=('pro-audio')
>provides=("${_pkgname}" "${_pkgname}=${pkgver//.r*/}")
>conflicts=("${_pkgname}")
>source=("${_pkgname}::git+https://github.com/ahlstromcj/${_pkgname}.git")
>md5sums=('SKIP')
>
>pkgver() {
>  cd "${srcdir}/${_pkgname}"
>  echo "$(git describe).r$(git rev-list --count HEAD).$(git rev-parse --short HEAD)"
>}
>
>build() {
>  cd "${srcdir}/${_pkgname}"
>  ./bootstrap
>  ./configure --prefix=/usr --enable-rtmidi
>  make
>}
>
>package() {
>  cd "${srcdir}/${_pkgname}"
>  make DESTDIR="${pkgdir}/" install
>}
>~~~
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/ahlstromcj/seq66/issues/22

-- 
Please remain calm, it's no use both of us being hysterical at the same time.
