### ISSUE TITLE
Problems with Qt during compilation

### ISSUE THREAD

**Issue by unfa** [ahlstromcj/seq66#23]
Hi!

I'm trying to build Seq66 on Manjaro Linux (KDE edition) and I'm running into this problem:

```
checking for Qt... yes:
    QT_CXXFLAGS=-pipe -O2 -Wall -Wextra -D_REENTRANT -fPIC -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I. -I/usr/include/qt -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtGui -I/usr/include/qt/QtCore -I. -I/usr/lib/qt/mkspecs/linux-g++ 
    QT_DIR=/usr/lib
    QT_LIBS=/usr/lib/libQt5Widgets.so /usr/lib/libQt5Gui.so /usr/lib/libQt5Core.so -lGL -lpthread  
    QT_MOC=/usr/bin/moc
    QT_RCC=/usr/bin/rcc
    QT_UIC=/usr/bin/uic
    QT_LRELEASE=/usr/bin/lrelease
    QT_LUPDATE=/usr/bin/lupdate
checking correct functioning of Qt installation... failure
configure: error: Failed to find matching components of a complete
                  Qt installation. Try using more options,
                  see ./configure --help.
```

What can I do?

**Comment by ahlstromcj** [comment]
You can look at config.log to hopefully see the command that failed.

Also, go to line 384 "Qt Builds" and make sure those DEPENDENCIES are
installed.  Note that it Debian those libraries' names end with "-dev".  I
don't know Manjaro conventions.

Then fully clean out the build and rebuild in the seq66 directory:

     $ ./bootstrap --full-clean
     $ ./bootstrap -er
     $ make &> make.log

and check out make.log for results.

If you still have issues, post your config.log.  Good luck!

-------- unfa 06:11 Fri 06 Nov      --------

>Hi!
>
>I'm trying to build Seq66 on Manjaro Linux (KDE edition) and I'm running into this problem:
>
>```
>checking for Qt... yes:
>    QT_CXXFLAGS=-pipe -O2 -Wall -Wextra -D_REENTRANT -fPIC -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I. -I/usr/include/qt -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtGui -I/usr/include/qt/QtCore -I. -I/usr/lib/qt/mkspecs/linux-g++
>    QT_DIR=/usr/lib
>    QT_LIBS=/usr/lib/libQt5Widgets.so /usr/lib/libQt5Gui.so /usr/lib/libQt5Core.so -lGL -lpthread
>    QT_MOC=/usr/bin/moc
>    QT_RCC=/usr/bin/rcc
>    QT_UIC=/usr/bin/uic
>    QT_LRELEASE=/usr/bin/lrelease
>    QT_LUPDATE=/usr/bin/lupdate
>checking correct functioning of Qt installation... failure
>configure: error: Failed to find matching components of a complete
>                  Qt installation. Try using more options,
>                  see ./configure --help.
>```
>
>What can I do?
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/ahlstromcj/seq66/issues/23

-- 
like:
	When being alive at the same time is a wonderful coincidence.

**Comment by unfa** [comment]
Thank you!

**Comment by unfa** [comment]
Hmm, I've tried to figure this out, but I can't find proper packages I need to install for Arch/Manjaro to satisfy the dependancies.
I have qt5-base and a lot of other packages QT-related installed:

![image](https://user-images.githubusercontent.com/491704/98379755-ee6fc000-2047-11eb-8848-058b96040e45.png)

I've checked the dependancies listed here: https://github.com/ahlstromcj/seq66/issues/22 and I'm satisfying those.

Here's my config.log file:

[config.log](https://github.com/ahlstromcj/seq66/files/5501844/config.log)

**Comment by mxmilkiib** [comment]
Does seq66-git in the AUR give an error on build?

**Comment by unfa** [comment]
I've tried using the AUR PKGBUILD (I see it has been submitted, nice!) - the result is the same, I have found this though whihc I missed before:

```
checking for sys/stat.h... (cached) yes
checking sys/sysctl.h usability... no
checking sys/sysctl.h presence... no
checking for sys/sysctl.h... no
```

I've tried this:

```
$ pkgfile sys/sysctl.h
```
With and without leading slash - but it returns nothing in both cases.

**Comment by mxmilkiib** [comment]
It would be just `pkgfile sysctl.h`.

**Comment by unfa** [comment]
Ah, thanks :D

I got this:

```
$ pkgfile sysctl.h
core/glibc
core/linux-api-headers
core/linux316-headers
core/linux414-headers
core/linux419-headers
core/linux44-headers
core/linux49-headers
core/linux53-headers
core/linux54-headers
core/linux55-headers
community/aarch64-linux-gnu-glibc
community/aarch64-linux-gnu-linux-api-headers
community/dietlibc
community/emscripten
community/gitlab
community/kernel-headers-musl
community/libopencm3
community/linux419-rt-headers
community/linux54-rt-headers
community/riscv64-linux-gnu-glibc
community/riscv64-linux-gnu-linux-api-headers
community/zig
```

I don't know what can I do with this though. I guess these are installed packages that own a file named `sysctl.h`?

**Comment by mxmilkiib** [comment]
Do you have `base-devel` installed?
