### ISSUE TITLE
Configure fails

### ISSUE THREAD

**Issue by grammoboy2** [ahlstromcj/seq66#25]
./configure --enable-release --enable-rtmidi
configure: WARNING: unrecognized options: --enable-release
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
/bin/bash: /home/debian/develop/seq66/aux-files/missing: No such file or directory
configure: WARNING: 'missing' script is too old or missing
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking for gcc-8... no
checking for gcc-7... no
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking whether make supports the include directive... yes (GNU style)
checking dependency style of gcc... gcc3
checking for g++-8... no
checking for g++-7... no
checking for g++... g++
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking dependency style of g++... gcc3
checking how to run the C++ preprocessor... g++ -E
checking whether ln -s works... yes
checking whether to build with mingw32 for a Windows host... checking major version... 0
checking minor version... 90
checking patchlevel... 0
checking how to print strings... printf
checking for a sed that does not truncate output... /usr/bin/sed
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for fgrep... /usr/bin/grep -F
checking for ld used by gcc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking the maximum length of command line arguments... 1572864
checking how to convert x86_64-pc-linux-gnu file names to x86_64-pc-linux-gnu format... func_convert_file_noop
checking how to convert x86_64-pc-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /usr/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for ar... ar
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /usr/bin/nm -B output from gcc object... ok
checking for sysroot... no
checking for a working dd... /usr/bin/dd
checking how to truncate binary pipes... /usr/bin/dd bs=4096 count=1
checking for mt... mt
checking if mt is a manifest tool... no
checking how to run the C preprocessor... gcc -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... no
checking for gcc option to produce PIC... -fPIC -DPIC
checking if gcc PIC flag -fPIC -DPIC works... yes
checking if gcc static flag -static works... yes
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... yes
checking how to run the C++ preprocessor... g++ -E
checking for ld used by g++... /usr/bin/ld -m elf_x86_64
checking if the linker (/usr/bin/ld -m elf_x86_64) is GNU ld... yes
checking whether the g++ linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking for g++ option to produce PIC... -fPIC -DPIC
checking if g++ PIC flag -fPIC -DPIC works... yes
checking if g++ static flag -static works... yes
checking if g++ supports -c -o file.o... yes
checking if g++ supports -c -o file.o... (cached) yes
checking whether the g++ linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking dynamic linker characteristics... (cached) GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking for ANSI C header files... (cached) yes
checking getopt.h usability... yes
checking getopt.h presence... yes
checking for getopt.h... yes
checking for string.h... (cached) yes
checking limits.h usability... yes
checking limits.h presence... yes
checking for limits.h... yes
checking stdarg.h usability... yes
checking stdarg.h presence... yes
checking for stdarg.h... yes
checking stdio.h usability... yes
checking stdio.h presence... yes
checking for stdio.h... yes
checking stddef.h usability... yes
checking stddef.h presence... yes
checking for stddef.h... yes
checking for stdlib.h... (cached) yes
checking for string.h... (cached) yes
checking for limits.h... (cached) yes
checking ctype.h usability... yes
checking ctype.h presence... yes
checking for ctype.h... yes
checking sys/time.h usability... yes
checking sys/time.h presence... yes
checking for sys/time.h... yes
checking time.h usability... yes
checking time.h presence... yes
checking for time.h... yes
checking errno.h usability... yes
checking errno.h presence... yes
checking for errno.h... yes
checking fcntl.h usability... yes
checking fcntl.h presence... yes
checking for fcntl.h... yes
checking for sys/stat.h... (cached) yes
checking sys/sysctl.h usability... yes
checking sys/sysctl.h presence... yes
checking for sys/sysctl.h... yes
checking syslog.h usability... yes
checking syslog.h presence... yes
checking for syslog.h... yes
checking for unistd.h... (cached) yes
checking for an ANSI C-conforming const... yes
checking for doxygen... doxygen
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for jack >= 0.90.0... yes
checking jack/session.h usability... yes
checking jack/session.h presence... yes
checking for jack/session.h... yes
JACK session support enabled.
JACK support enabled.
configure: LASH support disabled.
checking for liblo... yes
sessions/nsm library build enabled.
checking for ALSA CFLAGS... 
checking for ALSA LDFLAGS...  -lasound -lm -ldl -lpthread
checking for libasound headers version >= 0.9.0... found.
checking for snd_ctl_open in -lasound... yes
rtmidi engine build enabled.
checking for ALSA CFLAGS... 
checking for ALSA LDFLAGS...  -lasound -lm -ldl -lpthread -lasound -lm -ldl -lpthread
checking for libasound headers version >= 0.9.0... found.
checking for snd_ctl_open in -lasound... (cached) yes
checking for X... libraries , headers 
checking for gethostbyname... yes
checking for connect... yes
checking for remove... yes
checking for shmat... yes
checking for IceConnectionNumber in -lICE... yes
checking for Qt... yes:
    QT_CXXFLAGS=-pipe -O2 -Wall -Wextra -D_REENTRANT -fPIC -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I. -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ 
    QT_DIR=/usr/lib/x86_64-linux-gnu
    QT_LIBS=/usr/lib/x86_64-linux-gnu/libQt5Widgets.so /usr/lib/x86_64-linux-gnu/libQt5Gui.so /usr/lib/x86_64-linux-gnu/libQt5Core.so -lGL -lpthread  
    QT_MOC=/usr/bin/moc
    QT_RCC=/usr/bin/rcc
    QT_UIC=/usr/bin/uic
    QT_LRELEASE=/usr/bin/lrelease
    QT_LUPDATE=/usr/bin/lupdate
checking correct functioning of Qt installation... success
qt user-interface build enabled.
configure: PortMidi build disabled.
checking whether to enable gcov coverage tests... no
checking whether to enable gprof profiling... no
checking whether to enable gdb debugging... no
configure: Normal pthreads support
checking Running normal PTHREAD test... checking whether gcc is Clang... no
checking whether pthreads work with -pthread... yes
checking for joinable pthread attribute... PTHREAD_CREATE_JOINABLE
checking whether more special flags are required for pthreads... no
checking for PTHREAD_PRIO_INHERIT... yes
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: error: cannot find input file: `Makefile.in'

**Comment by ahlstromcj** [comment]
I think this one might be fixed.  I found one Makefile.in that was not checked
into git (the one in the doc/latex directory).

-------- grammoboy 13:58 Mon 09 Nov      --------

>
>
>
>` ./configure --enable-release --enable-rtmidi
>configure: WARNING: unrecognized options: --enable-release
>checking build system type... x86_64-pc-linux-gnu
>checking host system type... x86_64-pc-linux-gnu
>checking for a BSD-compatible install... /usr/bin/install -c
>checking whether build environment is sane... yes
>/bin/bash: /home/debian/develop/seq66/aux-files/missing: No such file or directory
>configure: WARNING: 'missing' script is too old or missing
>checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
>checking for gawk... gawk
>checking whether make sets $(MAKE)... yes
>checking whether make supports nested variables... yes
>checking for gcc-8... no
>checking for gcc-7... no
>checking for gcc... gcc
>checking whether the C compiler works... yes
>checking for C compiler default output file name... a.out
>checking for suffix of executables...
>checking whether we are cross compiling... no
>checking for suffix of object files... o
>checking whether we are using the GNU C compiler... yes
>checking whether gcc accepts -g... yes
>checking for gcc option to accept ISO C89... none needed
>checking whether gcc understands -c and -o together... yes
>checking whether make supports the include directive... yes (GNU style)
>checking dependency style of gcc... gcc3
>checking for g++-8... no
>checking for g++-7... no
>checking for g++... g++
>checking whether we are using the GNU C++ compiler... yes
>checking whether g++ accepts -g... yes
>checking dependency style of g++... gcc3
>checking how to run the C++ preprocessor... g++ -E
>checking whether ln -s works... yes
>checking whether to build with mingw32 for a Windows host... checking major version... 0
>checking minor version... 90
>checking patchlevel... 0
>checking how to print strings... printf
>checking for a sed that does not truncate output... /usr/bin/sed
>checking for grep that handles long lines and -e... /usr/bin/grep
>checking for egrep... /usr/bin/grep -E
>checking for fgrep... /usr/bin/grep -F
>checking for ld used by gcc... /usr/bin/ld
>checking if the linker (/usr/bin/ld) is GNU ld... yes
>checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
>checking the name lister (/usr/bin/nm -B) interface... BSD nm
>checking the maximum length of command line arguments... 1572864
>checking how to convert x86_64-pc-linux-gnu file names to x86_64-pc-linux-gnu format... func_convert_file_noop
>checking how to convert x86_64-pc-linux-gnu file names to toolchain format... func_convert_file_noop
>checking for /usr/bin/ld option to reload object files... -r
>checking for objdump... objdump
>checking how to recognize dependent libraries... pass_all
>checking for dlltool... no
>checking how to associate runtime and link libraries... printf %s\n
>checking for ar... ar
>checking for archiver @FILE support... @
>checking for strip... strip
>checking for ranlib... ranlib
>checking command to parse /usr/bin/nm -B output from gcc object... ok
>checking for sysroot... no
>checking for a working dd... /usr/bin/dd
>checking how to truncate binary pipes... /usr/bin/dd bs=4096 count=1
>checking for mt... mt
>checking if mt is a manifest tool... no
>checking how to run the C preprocessor... gcc -E
>checking for ANSI C header files... yes
>checking for sys/types.h... yes
>checking for sys/stat.h... yes
>checking for stdlib.h... yes
>checking for string.h... yes
>checking for memory.h... yes
>checking for strings.h... yes
>checking for inttypes.h... yes
>checking for stdint.h... yes
>checking for unistd.h... yes
>checking for dlfcn.h... yes
>checking for objdir... .libs
>checking if gcc supports -fno-rtti -fno-exceptions... no
>checking for gcc option to produce PIC... -fPIC -DPIC
>checking if gcc PIC flag -fPIC -DPIC works... yes
>checking if gcc static flag -static works... yes
>checking if gcc supports -c -o file.o... yes
>checking if gcc supports -c -o file.o... (cached) yes
>checking whether the gcc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
>checking whether -lc should be explicitly linked in... no
>checking dynamic linker characteristics... GNU/Linux ld.so
>checking how to hardcode library paths into programs... immediate
>checking whether stripping libraries is possible... yes
>checking if libtool supports shared libraries... yes
>checking whether to build shared libraries... yes
>checking whether to build static libraries... yes
>checking how to run the C++ preprocessor... g++ -E
>checking for ld used by g++... /usr/bin/ld -m elf_x86_64
>checking if the linker (/usr/bin/ld -m elf_x86_64) is GNU ld... yes
>checking whether the g++ linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
>checking for g++ option to produce PIC... -fPIC -DPIC
>checking if g++ PIC flag -fPIC -DPIC works... yes
>checking if g++ static flag -static works... yes
>checking if g++ supports -c -o file.o... yes
>checking if g++ supports -c -o file.o... (cached) yes
>checking whether the g++ linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
>checking dynamic linker characteristics... (cached) GNU/Linux ld.so
>checking how to hardcode library paths into programs... immediate
>checking for ANSI C header files... (cached) yes
>checking getopt.h usability... yes
>checking getopt.h presence... yes
>checking for getopt.h... yes
>checking for string.h... (cached) yes
>checking limits.h usability... yes
>checking limits.h presence... yes
>checking for limits.h... yes
>checking stdarg.h usability... yes
>checking stdarg.h presence... yes
>checking for stdarg.h... yes
>checking stdio.h usability... yes
>checking stdio.h presence... yes
>checking for stdio.h... yes
>checking stddef.h usability... yes
>checking stddef.h presence... yes
>checking for stddef.h... yes
>checking for stdlib.h... (cached) yes
>checking for string.h... (cached) yes
>checking for limits.h... (cached) yes
>checking ctype.h usability... yes
>checking ctype.h presence... yes
>checking for ctype.h... yes
>checking sys/time.h usability... yes
>checking sys/time.h presence... yes
>checking for sys/time.h... yes
>checking time.h usability... yes
>checking time.h presence... yes
>checking for time.h... yes
>checking errno.h usability... yes
>checking errno.h presence... yes
>checking for errno.h... yes
>checking fcntl.h usability... yes
>checking fcntl.h presence... yes
>checking for fcntl.h... yes
>checking for sys/stat.h... (cached) yes
>checking sys/sysctl.h usability... yes
>checking sys/sysctl.h presence... yes
>checking for sys/sysctl.h... yes
>checking syslog.h usability... yes
>checking syslog.h presence... yes
>checking for syslog.h... yes
>checking for unistd.h... (cached) yes
>checking for an ANSI C-conforming const... yes
>checking for doxygen... doxygen
>checking for pkg-config... /usr/bin/pkg-config
>checking pkg-config is at least version 0.9.0... yes
>checking for jack >= 0.90.0... yes
>checking jack/session.h usability... yes
>checking jack/session.h presence... yes
>checking for jack/session.h... yes
>JACK session support enabled.
>JACK support enabled.
>configure: LASH support disabled.
>checking for liblo... yes
>sessions/nsm library build enabled.
>checking for ALSA CFLAGS...
>checking for ALSA LDFLAGS...  -lasound -lm -ldl -lpthread
>checking for libasound headers version >= 0.9.0... found.
>checking for snd_ctl_open in -lasound... yes
>rtmidi engine build enabled.
>checking for ALSA CFLAGS...
>checking for ALSA LDFLAGS...  -lasound -lm -ldl -lpthread -lasound -lm -ldl -lpthread
>checking for libasound headers version >= 0.9.0... found.
>checking for snd_ctl_open in -lasound... (cached) yes
>checking for X... libraries , headers
>checking for gethostbyname... yes
>checking for connect... yes
>checking for remove... yes
>checking for shmat... yes
>checking for IceConnectionNumber in -lICE... yes
>checking for Qt... yes:
>    QT_CXXFLAGS=-pipe -O2 -Wall -Wextra -D_REENTRANT -fPIC -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I. -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++
>    QT_DIR=/usr/lib/x86_64-linux-gnu
>    QT_LIBS=/usr/lib/x86_64-linux-gnu/libQt5Widgets.so /usr/lib/x86_64-linux-gnu/libQt5Gui.so /usr/lib/x86_64-linux-gnu/libQt5Core.so -lGL -lpthread
>    QT_MOC=/usr/bin/moc
>    QT_RCC=/usr/bin/rcc
>    QT_UIC=/usr/bin/uic
>    QT_LRELEASE=/usr/bin/lrelease
>    QT_LUPDATE=/usr/bin/lupdate
>checking correct functioning of Qt installation... success
>qt user-interface build enabled.
>configure: PortMidi build disabled.
>checking whether to enable gcov coverage tests... no
>checking whether to enable gprof profiling... no
>checking whether to enable gdb debugging... no
>configure: Normal pthreads support
>checking Running normal PTHREAD test... checking whether gcc is Clang... no
>checking whether pthreads work with -pthread... yes
>checking for joinable pthread attribute... PTHREAD_CREATE_JOINABLE
>checking whether more special flags are required for pthreads... no
>checking for PTHREAD_PRIO_INHERIT... yes
>checking that generated files are newer than configure... done
>configure: creating ./config.status
>config.status: error: cannot find input file: `Makefile.in'`
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/ahlstromcj/seq66/issues/25

-- 
Never trust a child farther than you can throw it.

**Comment by grammoboy2** [comment]
seq66$ ./configure 
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
/bin/bash: /home/debian/develop/seq66/aux-files/missing: No such file or directory
configure: WARNING: 'missing' script is too old or missing
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking whether make supports the include directive... yes (GNU style)
checking dependency style of gcc... gcc3
checking for g++... g++
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking dependency style of g++... gcc3
checking how to run the C++ preprocessor... g++ -E
checking whether ln -s works... yes
checking whether to build with mingw32 for a Windows host... checking major version... 0
checking minor version... 91
checking patchlevel... 0
checking how to print strings... printf
checking for a sed that does not truncate output... /usr/bin/sed
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for fgrep... /usr/bin/grep -F
checking for ld used by gcc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking the maximum length of command line arguments... 1572864
checking how to convert x86_64-pc-linux-gnu file names to x86_64-pc-linux-gnu format... func_convert_file_noop
checking how to convert x86_64-pc-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /usr/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for ar... ar
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /usr/bin/nm -B output from gcc object... ok
checking for sysroot... no
checking for a working dd... /usr/bin/dd
checking how to truncate binary pipes... /usr/bin/dd bs=4096 count=1
checking for mt... mt
checking if mt is a manifest tool... no
checking how to run the C preprocessor... gcc -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... no
checking for gcc option to produce PIC... -fPIC -DPIC
checking if gcc PIC flag -fPIC -DPIC works... yes
checking if gcc static flag -static works... yes
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... yes
checking how to run the C++ preprocessor... g++ -E
checking for ld used by g++... /usr/bin/ld -m elf_x86_64
checking if the linker (/usr/bin/ld -m elf_x86_64) is GNU ld... yes
checking whether the g++ linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking for g++ option to produce PIC... -fPIC -DPIC
checking if g++ PIC flag -fPIC -DPIC works... yes
checking if g++ static flag -static works... yes
checking if g++ supports -c -o file.o... yes
checking if g++ supports -c -o file.o... (cached) yes
checking whether the g++ linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking dynamic linker characteristics... (cached) GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking for ANSI C header files... (cached) yes
checking getopt.h usability... yes
checking getopt.h presence... yes
checking for getopt.h... yes
checking for string.h... (cached) yes
checking limits.h usability... yes
checking limits.h presence... yes
checking for limits.h... yes
checking stdarg.h usability... yes
checking stdarg.h presence... yes
checking for stdarg.h... yes
checking stdio.h usability... yes
checking stdio.h presence... yes
checking for stdio.h... yes
checking stddef.h usability... yes
checking stddef.h presence... yes
checking for stddef.h... yes
checking for stdlib.h... (cached) yes
checking for string.h... (cached) yes
checking for limits.h... (cached) yes
checking ctype.h usability... yes
checking ctype.h presence... yes
checking for ctype.h... yes
checking sys/time.h usability... yes
checking sys/time.h presence... yes
checking for sys/time.h... yes
checking time.h usability... yes
checking time.h presence... yes
checking for time.h... yes
checking errno.h usability... yes
checking errno.h presence... yes
checking for errno.h... yes
checking fcntl.h usability... yes
checking fcntl.h presence... yes
checking for fcntl.h... yes
checking for sys/stat.h... (cached) yes
checking sys/sysctl.h usability... yes
checking sys/sysctl.h presence... yes
checking for sys/sysctl.h... yes
checking syslog.h usability... yes
checking syslog.h presence... yes
checking for syslog.h... yes
checking for unistd.h... (cached) yes
checking for an ANSI C-conforming const... yes
checking for doxygen... doxygen
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for jack >= 0.90.0... yes
JACK support enabled.
configure: LASH support disabled.
Sessions/NSM support enabled.
checking for liblo... yes
LIBLO support enabled.
checking for ALSA CFLAGS... 
checking for ALSA LDFLAGS...  -lasound -lm -ldl -lpthread
checking for libasound headers version >= 0.9.0... found.
checking for snd_ctl_open in -lasound... yes
rtmidi engine build enabled.
checking for ALSA CFLAGS... 
checking for ALSA LDFLAGS...  -lasound -lm -ldl -lpthread -lasound -lm -ldl -lpthread
checking for libasound headers version >= 0.9.0... found.
checking for snd_ctl_open in -lasound... (cached) yes
checking for X... libraries , headers 
checking for gethostbyname... yes
checking for connect... yes
checking for remove... yes
checking for shmat... yes
checking for IceConnectionNumber in -lICE... yes
checking for Qt... Info: creating stash file /tmp/.qmake.stash
yes:
    QT_CXXFLAGS=-pipe -O2 -Wall -Wextra -D_REENTRANT -fPIC -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I. -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ 
    QT_DIR=/usr/lib/x86_64-linux-gnu
    QT_LIBS=/usr/lib/x86_64-linux-gnu/libQt5Widgets.so /usr/lib/x86_64-linux-gnu/libQt5Gui.so /usr/lib/x86_64-linux-gnu/libQt5Core.so -lGL -lpthread  
    QT_MOC=/usr/bin/moc
    QT_RCC=/usr/bin/rcc
    QT_UIC=/usr/bin/uic
    QT_LRELEASE=/usr/bin/lrelease
    QT_LUPDATE=/usr/bin/lupdate
checking correct functioning of Qt installation... success
qt user-interface build enabled.
configure: PortMidi build disabled.
checking whether to enable gcov coverage tests... no
checking whether to enable gprof profiling... no
checking whether to enable gdb debugging... no
configure: Normal pthreads support
checking Running normal PTHREAD test... checking whether gcc is Clang... no
checking whether pthreads work with -pthread... yes
checking for joinable pthread attribute... PTHREAD_CREATE_JOINABLE
checking whether more special flags are required for pthreads... no
checking for PTHREAD_PRIO_INHERIT... yes
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating libseq66/Makefile
config.status: creating libseq66/include/Makefile
config.status: creating libseq66/src/Makefile
config.status: creating libsessions/Makefile
config.status: creating libsessions/include/Makefile
config.status: creating libsessions/src/Makefile
config.status: creating m4/Makefile
config.status: creating man/Makefile
config.status: creating seq_portmidi/Makefile
config.status: creating seq_portmidi/include/Makefile
config.status: creating seq_portmidi/src/Makefile
config.status: creating seq_rtmidi/Makefile
config.status: creating seq_rtmidi/include/Makefile
config.status: creating seq_rtmidi/src/Makefile
config.status: creating seq_qt5/Makefile
config.status: creating seq_qt5/include/Makefile
config.status: creating seq_qt5/forms/Makefile
config.status: creating seq_qt5/src/Makefile
config.status: creating resources/pixmaps/Makefile
config.status: creating Seq66qt5/Makefile
config.status: creating Seq66cli/Makefile
config.status: creating data/Makefile
config.status: creating doc/Makefile
config.status: creating doc/dox/Makefile
config.status: creating doc/latex/Makefile
config.status: error: cannot find input file: `doc/latex/tex/Makefile.in'

**Comment by grammoboy2** [comment]
Should be doc/latex/Makefile.in ?

Removing tex from the path?

**Comment by ahlstromcj** [comment]
Doh!  I forgot to add doc/latex/tex/Makefile.in !  (I'm not a big fan of having
to have all these Makefile.in's, though).

If you have all the dev tools installed, including libtool, you can do

    $ ./bootstrap --full-clean
    $ ./bootstrap -er
    $ make                       (or $ make &> make.log)

If you have QtCreator/qmake installed, you can copy the script "qbuild" in
the "contrib/scripts" directory to your path, then do:

    $ cd .../seq66
    $ cd ..
    $ mkdir shadow
    $ cd shadow
    $ qbuild rtmidi
    $ make

Or wait until the end of the day when I can update the master with a number of
fixes.

Maybe I can attach the Makefile.in, stay tuned.

-------- grammoboy 05:28 Wed 25 Nov      --------

>Should be doc/latex/Makefile.in ?
>
>Removing tex from the path?
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/ahlstromcj/seq66/issues/25#issuecomment-733706177

-- 
Man is an animal that makes bargains: no other animal does this--
no dog exchanges bones with another.
		-- Adam Smith

**Comment by grammoboy2** [comment]
Thx, I'll wait patiently.

**Comment by ahlstromcj** [comment]
[Makefile.txt](https://github.com/ahlstromcj/seq66/files/5597013/Makefile.txt)

Try this one.  Rename it to Makefile.in and copy it to doc/latex/tex.

**Comment by grammoboy2** [comment]
Progress, but:


seq66$ make
CDPATH="${ZSH_VERSION+.}:" && cd . && aclocal-1.16 -I m4
  cd . && automake-1.16 --foreign
configure.ac:53: error: required file 'aux-files/compile' not found
configure.ac:53:   'automake --add-missing' can install 'compile'
configure.ac:27: error: required file 'aux-files/missing' not found
configure.ac:27:   'automake --add-missing' can install 'missing'
make: *** [Makefile:537: Makefile.in] Error 1

**Comment by ahlstromcj** [comment]
Dang.  You can try running those commands.  But more errors might come up.  I
will work on getting configure to work properly, and get a proper setup for the
end user.  Thanks, and sorry for the big hiccups.

-------- grammoboy 05:48 Wed 25 Nov      --------

>Progress, but:
>
>
>seq66$ make
>CDPATH="${ZSH_VERSION+.}:" && cd . && aclocal-1.16 -I m4
>  cd . && automake-1.16 --foreign
>configure.ac:53: error: required file 'aux-files/compile' not found
>configure.ac:53:   'automake --add-missing' can install 'compile'
>configure.ac:27: error: required file 'aux-files/missing' not found
>configure.ac:27:   'automake --add-missing' can install 'missing'
>make: *** [Makefile:537: Makefile.in] Error 1
>
>
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/ahlstromcj/seq66/issues/25#issuecomment-733716949

-- 
Never test for an error condition you don't know how to handle.
		-- Steinbach

**Comment by grammoboy2** [comment]
I'll just wait patiently ;)
thx

**Comment by ahlstromcj** [comment]
Okay, I made, tested, uploaded, download, and tested a tarball in a temp
directory.

Go to GitHub: ahlstromcj / sequencer64-packages / seq66 / 0.91 and download the
tarball seq66-nsm-rtmidi-0.91rc1.tar.xz from there.  It's about 5.6Mb in size.
Let me know of any issues; make sure automake is installed on your system.
Good luck!

-------- grammoboy 06:09 Wed 25 Nov      --------

>I'll just wait patiently ;)
>thx
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/ahlstromcj/seq66/issues/25#issuecomment-733728867

-- 
Your supervisor is thinking about you.

**Comment by grammoboy2** [comment]
Builds and installs fine. Thanks.

**Comment by grammoboy2** [comment]
> Builds and installs fine. Thanks.


But how do I start it?

$ seq
seq        seq24-nsm


$ seq24-nsm
must be run under nsm-proxy

**Comment by grammoboy2** [comment]
For now I take a 'testing break'. Will try the next release. Ciao.
>

**Comment by ahlstromcj** [comment]
The Qt version (the normal version) of seq66 is called qseq66.  The command line version (if you build it) is "seq66cli".  There are also versions "qpseq66" (the portmidi engine build for Windows) and "qrseq66" (the rtmidi version that I build using qmake because one of my machines wouldn't build a normal debug version).  By the way, the next release, 0.91.1, is in master now.  Have fun!

Maybe I should have "make install" make a soft-link called "seq66" that points to the installed version of "qseq66".  So many things to think of!

**Comment by grammoboy2** [comment]
builds fine now, thx
