### ISSUE TITLE
Freeze/crash after selecting 'Import into session'

### ISSUE THREAD

**Issue by mxmilkiib** [ahlstromcj/seq66#26]
A file dialog opens up but the app freezes and nothing can be selected then it crashes if i don't kill it first.

https://gist.github.com/7f9e37fb6c37be45d803f589592fd17f

**Comment by ahlstromcj** [comment]
This is a tough one, not sure why updating the recent-files menu's text causes
this crash.  Still poking at it, finding other minor issues along the way.
Thanks for reporting!

-------- Milkii Brewster 22:18 Wed 11 Nov      --------

>A file dialog opens up but the app freezes and nothing can be selected then it crashes if i don't kill it first.
>
>https://gist.github.com/7f9e37fb6c37be45d803f589592fd17f
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/ahlstromcj/seq66/issues/26

-- 
He had that rare weird electricity about him -- that extremely wild and heavy
presence that you only see in a person who has abandoned all hope of ever
behaving "normally."
		-- Hunter S. Thompson, "Fear and Loathing '72"

**Comment by ahlstromcj** [comment]
Tentatively fixed in the nsm branch by not updating the recent-files menu in
this use-case.

-------- Milkii Brewster 22:18 Wed 11 Nov      --------

>A file dialog opens up but the app freezes and nothing can be selected then it crashes if i don't kill it first.
>
>https://gist.github.com/7f9e37fb6c37be45d803f589592fd17f
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/ahlstromcj/seq66/issues/26

-- 
Go ahead, capitalize the T on technology, deify it if it will make you feel
less responsible -- but it puts you in with the neutered, brother, in with
the eunuchs keeping the harem of our stolen Earth for the numb and joyless
hardons of human sultans, human elite with no right at all to be where they
are --"
		-- Thomas Pynchon, _Gravity's Rainbow_

**Comment by mxmilkiib** [comment]
I can select a file, and it imports to the session and I get the dialog with the tick box. I then save the NSM session, close it, then reopen it but seq66 comes up without any MIDI loaded.

**Comment by ahlstromcj** [comment]
Looks like I need to add a "current MIDI file" to the configuration. You
can also try making a playlist, but I am still working out the last nits in
that process. Last time I checked it worked, but I have been proven capable
of breaking things. :-D
