### ISSUE TITLE
NSM: pattern state isn't recalled with session

### ISSUE THREAD

**Issue by mxmilkiib** [ahlstromcj/seq66#27]
The project MIDI file is saved and recalled with the session now, but the on/off state of the patterns at the point of saving is not recalled on session start.

**Comment by ahlstromcj** [comment]
I added a configuration item in the "mutes" file, mute-group-selected, which will preserve the last selected mute-group, whether it was saved in the MIDI file or in the "mutes" file.  If not -1, that mute-group will be loaded at startup.  This works in normal operation or in an NSM session.  Let me know of any lapses to fix or tweaks that are need.  Included in the master and nsm branches right now.  Note that you do need to define a mute-group and apply it before exiting Seq66.

**Comment by mxmilkiib** [comment]
If I start a fresh session (using nsm-legacy-gui provided with the main new-session-manager package) and add qseq66, it opens up the MIDI file from the previous session.

If I save, I get this console output;
```
[nsmd] ../src/nsmd.cpp:761 command_client_to_save(): Telling seq66.nAIHA to save
[nsmd] ../src/nsmd.cpp:642 wait_for_replies(): Waiting for clients to reply to commands[Writing Seq66 MIDI file 192 PPQN: '/home/milk/media/audio/projects/carla/carla-modular-synth-tests/boom3/boom3.midi']

[Wrote MIDI file: '/home/milk/media/audio/projects/carla/carla-modular-synth-tests/boom3/boom3.midi']
[Save session: 'Options']
[Writing 'rc': '/home/milk/media/audio/projects/NSM/test-seq66-nov-2020/seq66.nAIHA/config/qseq66.rc']
[Writing 'ctrl': '/home/milk/media/audio/projects/NSM/test-seq66-nov-2020/seq66.nAIHA/config/qseq66.ctrl']
[Writing 'mutes': '/home/milk/media/audio/projects/NSM/test-seq66-nov-2020/seq66.nAIHA/config/qseq66.mutes']
[Writing 'usr': '/home/milk/media/audio/projects/NSM/test-seq66-nov-2020/seq66.nAIHA/config/qseq66.usr']
[Save session: 'Play-list']
[Play-list save: '/home/milk/media/audio/projects/NSM/test-seq66-nov-2020/seq66.nAIHA/config/empty.playlist']
[Writing 'playlist': '/home/milk/media/audio/projects/NSM/test-seq66-nov-2020/seq66.nAIHA/config/empty.playlist']
[Save session: 'Note-mapper']
[Writing 'drums': '/home/milk/media/audio/projects/NSM/test-seq66-nov-2020/seq66.nAIHA/config/empty.drums']
[nsmd] ../src/nsmd.cpp:2136 osc_reply(): Client "seq66.nAIHA" replied with: OK:  in 21.720000ms
```

Then upon trying to reload, I get;
```
[Play-list: Empty Sample: song '/home/milk/media/audio/projects/NSM/test-seq66-nov-2020/seq66.nAIHA/midi/""' missing; check relative directories.!!]
```

**Comment by mxmilkiib** [comment]
If I start the session and do New MIDI File..., I get a blank project. I create two patterns, enable one and leave the other muted, do a save and close, then I reopen the session, the new MIDI file has persisted but both patterns in it are muted.

**Comment by ahlstromcj** [comment]
The armed status isn't something that modifies a file.  If you want to save
that status, you can learn the pattern into a mute-group.  That mute-group
number is saved in the "mutes" file, and, if not -1, then it is applied when
the performer starts.  Check out the documentation in qseq66.mutes.

-------- Milkii Brewster 14:14 Sat 28 Nov      --------

>If I start the session and do New MIDI File..., I get a blank project. I create two patterns, enable one and leave the other muted, do a save and close, then I reopen the session, the new MIDI file has persisted but both patterns in it are muted.
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/ahlstromcj/seq66/issues/27#issuecomment-735297260

-- 
"This isn't brain surgery; it's just television."
		-- David Letterman

**Comment by ahlstromcj** [comment]
I will try to figure out what's happening. I assume you have set up a playlist
with a bunch of MIDI files in the normal Seq66 config directory, then loaded
qseq66 in a new NSM sesion, and that it copies the config files to the
.../seq66.nAIHA/config directory and the MIDI files  in the seq66.nAIHA/midi
directory.  Any other details?

-------- Milkii Brewster 14:10 Sat 28 Nov      --------

>If I start a fresh session (using nsm-legacy-gui provided with the main new-session-manager package) and add qseq66, it opens up the MIDI file from the previous session.
>
>If I save, I get this console output;
>```
>[nsmd] ../src/nsmd.cpp:761 command_client_to_save(): Telling seq66.nAIHA to save
>[nsmd] ../src/nsmd.cpp:642 wait_for_replies(): Waiting for clients to reply to commands[Writing Seq66 MIDI file 192 PPQN: '/home/milk/media/audio/projects/carla/carla-modular-synth-tests/boom3/boom3.midi']
>
>[Wrote MIDI file: '/home/milk/media/audio/projects/carla/carla-modular-synth-tests/boom3/boom3.midi']
>[Save session: 'Options']
>[Writing 'rc': '/home/milk/media/audio/projects/NSM/test-seq66-nov-2020/seq66.nAIHA/config/qseq66.rc']
>[Writing 'ctrl': '/home/milk/media/audio/projects/NSM/test-seq66-nov-2020/seq66.nAIHA/config/qseq66.ctrl']
>[Writing 'mutes': '/home/milk/media/audio/projects/NSM/test-seq66-nov-2020/seq66.nAIHA/config/qseq66.mutes']
>[Writing 'usr': '/home/milk/media/audio/projects/NSM/test-seq66-nov-2020/seq66.nAIHA/config/qseq66.usr']
>[Save session: 'Play-list']
>[Play-list save: '/home/milk/media/audio/projects/NSM/test-seq66-nov-2020/seq66.nAIHA/config/empty.playlist']
>[Writing 'playlist': '/home/milk/media/audio/projects/NSM/test-seq66-nov-2020/seq66.nAIHA/config/empty.playlist']
>[Save session: 'Note-mapper']
>[Writing 'drums': '/home/milk/media/audio/projects/NSM/test-seq66-nov-2020/seq66.nAIHA/config/empty.drums']
>[nsmd] ../src/nsmd.cpp:2136 osc_reply(): Client "seq66.nAIHA" replied with: OK:  in 21.720000ms
>```
>
>Then upon trying to reload, I get;
>```
>[Play-list: Empty Sample: song '/home/milk/media/audio/projects/NSM/test-seq66-nov-2020/seq66.nAIHA/midi/""' missing; check relative directories.!!]
>```
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/ahlstromcj/seq66/issues/27#issuecomment-735296806

-- 
Colors may fade in time.

**Comment by ahlstromcj** [comment]
Added the ability to specify the last-active mute-group for restoring on startup.  See the [mute-group-flags] section and the mute-group-selected variable in the qseq66.mutes file. Starts with version 0.91.1.
