### ISSUE TITLE
Vertical scroll Pattern Editor window binding defaults

### ISSUE THREAD

**Issue by twerq** [ahlstromcj/seq66#3]
Open loop Pattern Editor window. On mouse wheel scroll event

Expected:
Piano-roll and notes sheet  scrolls vertically

Actual:
No visual effect

In Edit tab mouse wheel works as expected.

Seq66 ver. 0.90.1 from source
> Build features:
>   C++ version 201402
>   Native JACK/ALSA (rtmidi) on
>   Event editor on
>   Vector for event list on
>   Follow progress bar on
>   Highlight edit pattern on
>   JACK session on
>   JACK support on
>   LASH support OBSOLETE, REMOVED
>   MIDI vector (vs list) on
>   Seq32 chord generator on
>   Seq32 LFO window on
>   Seq32 menu buttons on
>   Seq32 transpose on
>   BPM Tap button on
>   Solid piano-roll grid on
>   Optional pattern coloring on
>   Song performerance recording on
>   Box song selection on
>   Pause support on
>   Save time-sig/tempo on
>   Debug code on
>   64-bit support enabled
> 
> Options are enabled/disabled via the configure script,
> libseq66/include/seq66_features.hpp, or the build-specific
> seq66-config.h file in include or in include/qt/portmidi

**Comment by ahlstromcj** [comment]
Thanks for the report!  I am glad someone is using this new version of the SeqXX line of apps.  I'm still dealing with outside stuff due to moving, but will hopefully be able to do more work on it as we get settled in.  Thanks again!

**Comment by ahlstromcj** [comment]
Finally go around to this one. We had to disable mouse-wheel scrolling for this reason: In qseqkeys, we did not want the scroll wheel to accidentally scroll the piano keys vertically.  Same for qscrollmaster, qseqeditframe64, except that we note wheelEvent() is not called for some reason.  One way around this issue might be to somehow pass child scrolling up to the qscrollmaster class, e.g. via a signal.

For now, we have mitigated this issue by enabling the scroll wheel in the pattern and song piano rolls, and disabled it in qseqdata, qseqtime, qstriggereditor, qperfnames, and qpertime.

So, the scroll wheel will work in the large piano rolls, but not in the smaller panes at the top, bottom, or left side of the piano roll.  This fix is currently in the portfix branch, and will be in master for version 0.99.4.

I will eventually look into emitting a scroll signal.

**Comment by ahlstromcj** [comment]
Another thing to look into for this issue is implement horizontal and vertical zoom via the scroll wheel.  I assume that would require using Shift to modify the scroll wheel action.  In the meantime, there are keystrokes in the piano rolls to effect zoom in both directions.  Stay tuned.

**Comment by twerq** [comment]
Sorry to say, I'm no longer into the seq66.

**Comment by ahlstromcj** [comment]
I think this is as good as it's gonna get. Click the piano roll to use the scrolling wheels.
