### ISSUE TITLE
Managing pattern colors with a pallette

### ISSUE THREAD

**Issue by unfa** [ahlstromcj/seq66#30]
I've finally managed to install Seq66 on Manjaro (from AUR) and I would like to use it for my next monthly livestream (tomorrow).
So I'm gonna report some issues as I'm testing it and preparing :)

Currently the colors available for patterns are quite a mess.

The "dark colors" are not really darker, but are less saturated instead.
I think assigning colors would be way better done with a retractable pallet panel (i imagine it above the transport controls, but below the set grid), where the user can drag'n' drop the color to assign it.

The colors could be stored as pallet reference and changing the palette would change the colors visible.
The default palette could have a bunch of colors, but it'd be good if users can delete and add more colors if need be.

A system-provided color picker dialog could be used for colors allowing for Hue/Saturation/Value manipulation.

**Comment by ahlstromcj** [comment]
The coloring is indeed ad hoc.  I did the minimum necessary to support colors.
I really don't want to encumber the application with a color-picking GUI.
I am willing to write the palette to a new "*.palette" configuration file, and
let the user tweak the file.

If someone want to upgrade the (normally not built) Seqtool in the project to
do this, that's fine by me.

I do have to refamiliarize myself with the existing palette scheme.  But I
currently have a request for set-arming handling that I want to put to bed
first.

I appreciate your feedback!

-------- unfa 08:12 Sat 05 Dec      --------

>I've finally managed to install Seq66 on Manjaro (from AUR) and I would like to use it for my next monthly livestream (tomorrow).
>So I'm gonna report some issues as I'm testing it and preparing :)
>
>Currently the colors available for patterns are quite a mess.
>
>The "dark colors" are not really darker, but are less saturated instead.
>I think assigning colors would be way better done with a retractable pallet panel (i imagine it above the transport controls, but below the set grid), where the user can drag'n' drop the color to assign it.
>
>The colors could be stored as pallet reference and changing the palette would change the colors visible.
>The default palette could have a bunch of colors, but it'd be good if users can delete and add more colors if need be.
>
>A system-provided color picker dialog could be used for colors allowing for Hue/Saturation/Value manipulation.
>
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/ahlstromcj/seq66/issues/30

-- 
A new koan:
	If you have some ice cream, I will give it to you.
	If you have no ice cream, I will take it away from you.
It is an ice cream koan.

**Comment by ahlstromcj** [comment]
Man, I really beefed up the palette support!  You still have to edit a text file (*.palette), but have a fair amount of control and extra colors now.  Documented in the PDF user manual which is now included with the source code and installation.
