### ISSUE TITLE
Pattern text readability on bright backgrounds

### ISSUE THREAD

**Issue by unfa** [ahlstromcj/seq66#31]
The default color for new patters is yellow - text being silver on this background is practically impossible to read.

![image](https://user-images.githubusercontent.com/491704/101248070-1290f080-371d-11eb-9926-64a7e3d45117.png)

I thin ka simple solution would be to draw  the text in pure white, having a pure black rectangle underneath, drawn with 75% opacity against the tile background color

![image](https://user-images.githubusercontent.com/491704/101250627-eaee5800-371d-11eb-8c7e-26969292203f.png)

This will ensure the text is readable even on pure white background.
Same goes for the MIDI data drawn, but maybe let's tackle one thing at a time.

**Comment by ahlstromcj** [comment]
Yeah, yellow is meant for totally empty patterns (just text info).  I will
eventually look at the text coloring and try to implement a text/background
palette.

To be frank, the coloring is a low priority for me.  But I will revisit it
soon!  Thanks!

-------- unfa 08:20 Sat 05 Dec      --------

>The default color for new patters is yellow - text being silver on this background is practically impossible to read.
>
>![image](https://user-images.githubusercontent.com/491704/101248070-1290f080-371d-11eb-9926-64a7e3d45117.png)
>
>I thin ka simple solution would be to draw  the text in pure white, having a pure black rectangle underneath, drawn with 75% opacity against the tile background color
>
>![image](https://user-images.githubusercontent.com/491704/101250627-eaee5800-371d-11eb-8c7e-26969292203f.png)
>
>This will ensure the text is readable even on pure white background.
>Same goes for the MIDI data drawn, but maybe let's tackle one thing at a time.
>
>
>
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/ahlstromcj/seq66/issues/31

-- 
Here is a test to find whether your mission on earth is finished:
if you're alive, it isn't.

**Comment by unfa** [comment]
I see - thank you for working on this live sequencer!
I really hope it can see a wider adoption int eh community, as it seems to be the best option for live MIDI loop work.
I want to give it another go and try some live music soon.

**Comment by ahlstromcj** [comment]
Based on the new 'palette' file support, you can change many colors, including foreground colors, so I believe this is worth closing.  Thanks for driving me to improve this feature!
