### ISSUE TITLE
NSM not working here

### ISSUE THREAD

**Issue by grammoboy2** [ahlstromcj/seq66#33]
Don't know if it suppose to work already, but starting qseq66 in NSM, make a change, save session, close session, open session.

Doesn't work here. Just a empty qseq66

**Comment by ahlstromcj** [comment]
Can you list an exact series of steps, and what version you're using?  Thanks!

-------- grammoboy 11:57 Thu 10 Dec      --------

>Don't know if it suppose to work already, but starting qseq66 in NSM, make a change, save session, close session, open session.
>
>Doesn't work here. Just a empty qseq66
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/ahlstromcj/seq66/issues/33

-- 
The key to building a superstar is to keep their mouth shut.  To reveal
an artist to the people can be to destroy him.  It isn't to anyone's
advantage to see the truth.
		-- Bob Ezrin, rock music producer

**Comment by ahlstromcj** [comment]
One thing to do is, after you have created the session, is to click the Save
button in NSM.  The session.nsm file does not exist until then.  I'll follow up
on this issue eventually, deeply mired in another issue right now.

-------- grammoboy 11:57 Thu 10 Dec      --------

>Don't know if it suppose to work already, but starting qseq66 in NSM, make a change, save session, close session, open session.
>
>Doesn't work here. Just a empty qseq66
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/ahlstromcj/seq66/issues/33

-- 
It does not matter if you fall down as long as you pick up something
from the floor while you get up.

**Comment by ahlstromcj** [comment]
I think this is fixed, just tested it.  Will merge to create version 0.91.3 soon, stay tuned.

**Comment by grammoboy2** [comment]
Sorry, doesn't work. Add qseq66 to Non-Session-Manager. Add pattern. Save. Close. Restart. -> Clean sheet.

**Comment by ahlstromcj** [comment]
I cannot duplicate your creation issue.  Here are my exact steps, using the
latest version of Seq66 from GitHub, VERSION 0.91.3 (I suspect that earlier
versions MIGHT NOT WORK):

1. I started with configuration files qseq66.* in ~/.config/seq66.  However, if
    they are not present, they are still created later in the process.

2. Run non-session-manager.

3. Click non's "New" button to create a new session called "Test-3".

4. Click non's "Add Client to Session" button, and enter "qseq66" (mine is
    stored in /usr/local/bin).  The qseq66 application starts, and at this
    point, we have:

		$ ls -RF NSM\ Sessions/Test-3/
		'NSM Sessions/Test-3/':
		seq66.nFWQK/  session.nsm

		'NSM Sessions/Test-3/seq66.nFWQK':
		config/  midi/

		'NSM Sessions/Test-3/seq66.nFWQK/config':
		qseq66.ctrl  qseq66.drums  qseq66.mutes  qseq66.rc  qseq66.usr

		'NSM Sessions/Test-3/seq66.nFWQK/midi':

    Note that session.nsm is empty, and there is no MIDI file.

5. Then, I add a new pattern, add a couple notes, then click
    File / Save to save the tune.  It DOES NOT save the tune, because at that
    point it does not have a name.  [I consider this to be a BUG, there should
    be a default file-name already in place, or a prompt for a filename.]
    So I do File / New MIDI File...  and make a pattern and save, and it works.
    At this point:

         $ ls NSM\ Sessions/Test-3/seq66.nFWQK/midi/
         newtune.midi

    and session.nsm is still empty.

6. In the NSM GUI, click Save at the top of the GUI. Now the session.nsm file
    has eq66:qseq66:nFWQK in it.

7. Just for kicks, I click the SAVE button for the Test-3 session, and in the
    console running non-session-manager I can see that qseq66 writes the files
    and replies back to NSM.

8. Lastly, I click the Stop block in the Test-3 session.  Again qseq66 writes
    its configuration files, and then it terminates.  The other option, File /
    Quit works as expected.

So apart from that BUG noted above, it's working fine for me.  I must emphasize
that my test is done with 0.91.3 which I checked in a day or two ago.

As for your other issue, as far as I can tell I am following the API
documentation strictly.  There is nothing wrong with being able to edit all the
parameters.  When the configuration is save, it goes into the correct NSM
Sessions directory, and will be used the next time the session is started.
But now I see your pictures, which tells me that the directory entries should
be read-only when running under an NSM session.  I had overlooked that!

Anyway, going through this exercise helped me beef up the documentation and
also unearthed a couple of other issues, so I thank you!

-------- grammoboy 11:57 Thu 10 Dec      --------

>Don't know if it suppose to work already, but starting qseq66 in NSM, make a change, save session, close session, open session.
>
>Doesn't work here. Just a empty qseq66
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/ahlstromcj/seq66/issues/33

-- 
Stop searching forever.  Happiness is unattainable.

**Comment by ahlstromcj** [comment]
@grammoboy2 Any more news on this issue?  Or are you sick of trying to get it to work :-)?

**Comment by grammoboy2** [comment]
Will do some testing this week ;)
