### ISSUE TITLE
NSM: Being able to edit session parameters manually, not according to NSM API.

### ISSUE THREAD

**Issue by grammoboy2** [ahlstromcj/seq66#35]
In Seq66 it seems I can edit all kind of parameters from the GUI. I think this is problematic. The idea of NSM is to keep everything in one Session folder.

http://non.tuxfamily.org/nsm/API.html
See 'save as' and 'data storage'

**Comment by grammoboy2** [comment]
![seq66nsm0](https://user-images.githubusercontent.com/378249/102599361-a7ccb580-411d-11eb-967d-85089944b5df.png)

![seq66nsm1](https://user-images.githubusercontent.com/378249/102599368-abf8d300-411d-11eb-9704-14aa6e6edf60.png)

**Comment by grammoboy2** [comment]
The NSM API gives you some strict rules. That's one of the reasons why NSM works as a session manager. It only works if applications follow the API closely.

**Comment by ahlstromcj** [comment]
Those edit fields are read-only.  In the "optimizing" branch I made them looked "disabled" to avoid confusion.  Will merge to master in a day or two.  Tons o' fixes.  Thanks for the feedback!

**Comment by ahlstromcj** [comment]
@grammoboy2 Just updated the master to 0.92.1, the latest.  If you still see any backdoors or bugs re NSM, don't hesitate to report them.  Thanks!
