### ISSUE TITLE
README doesn't describe seq66

### ISSUE THREAD

**Issue by mxmilkiib** [ahlstromcj/seq66#36]
The README intro currently starts from a "this is a seq24/sequencer64 reboot" perspective, but does not actually explain what that format is. Maybe something like;

Seq66 is a MIDI sequencer and live looper with a hardware sampler-like grid pattern interface, MIDI automation for live performance, with sets and playlists for song management and a scale/chord aware piano-roll interface and song editor for creative composition. Based on the classic Seq24, Seq66 is a refactoring of the Qt version of Sequencer64 / Kepler34 with modern C++. Supports NSM (New Session Manager) on Linux, can also be run headless.

**Comment by ahlstromcj** [comment]
I have updated the README, which another user updated to README.md.  I still keep adding tweaks to the description, but will close this one out.  Thanks for all your reports!  Keep 'em coming!
