### ISSUE TITLE
seq66/sequencer64 choice

### ISSUE THREAD

**Issue by henning** [ahlstromcj/seq66#38]
I think I need some guidance about the differences between the two current implementations to chose which one I shall try building and start using.

I had been using seq24 a long time ago and was away from music making and also Linux for a while... now I want to get back into it, and am looking for  using this great software, but the existence of two updated versions in parallel confuses me a bit on which to chose. 

I think I understand seq66 has an added looper feature, which I assume means it can directly record/play audio files.
I am not sure if I need that feature, so I'd be interested to understand am I better of to try sequencer64 when I dont need audio looping? 
Or am I generally better off using seq66 because it has an improved UI or something else while having the same midi features as sequencer64 and it might become the only version supported sometime? 

Thanks in advance, and sorry if the answer is already written in some obvious place that I failed to see - I skimmed through readmes and docs and couldn't answer the questions myself, as both programs seem to be in active development, and I thought I ask before starting building the software (i dont find binaries for the seq66 version that is mentioned in the "about" text , so I'd like to build the latest tag).

**Comment by ahlstromcj** [comment]
If you haven't used and gotten used to Sequencer64 yet, I'd opt for the newer
product, Seq66.  It's a bit more lean and handles theming better, and I am
continually trying to improve it. Currently documenting it and finding a lot of
bugs along the way :-(.

Sequencer64 is, for me, only in maintenance mode.... bug fixes and some
backports where there's not a lot of refactoring needed.

If you run into any showstoppers with Seq66, you can back-track to Sequencer64.
They're fairly similar.  Sequencer64 has a lot of features I decided were a bit
too much to keep around.

Oh, neither app handles audio loops, just MIDI.  I'll make that more clear in
the README.  Have fun, and feel free to report bugs and other dissatisfaction.

-------- Henning Sprang 17:25 Sun 31 Jan      --------

>I think I need some guidance about the differences between the two current implementations to chose which one I shall try building and start using.
>
>I had been using seq24 a long time ago and was away from music making and also Linux for a while... now I want to get back into it, and am looking for  using this great software, but the existence of two updated versions in parallel confuses me a bit on which to chose.
>
>I think I understand seq66 has an added looper feature, which I assume means it can directly record/play audio files.
>I am not sure if I need that feature, so I'd be interested to understand am I better of to try sequencer64 when I dont need audio looping?
>Or am I generally better off using seq66 because it has an improved UI or something else while having the same midi features as sequencer64 and it might become the only version supported sometime?
>
>Thanks in advance, and sorry if the answer is already written in some obvious place that I failed to see - I skimmed through readmes and docs and couldn't answer the questions myself, as both programs seem to be in active development, and I thought I ask before starting building the software (i dont find binaries for the seq66 version that is mentioned in the "about" text , so I'd like to build the latest tag).
>
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/ahlstromcj/seq66/issues/38

-- 
A woman was in love with fourteen soldiers.  It was clearly platoonic.

**Comment by ahlstromcj** [comment]
Thanks @lupin3rd for requesting this package!  My guess is that, as of 0.92.1 (today), I've got about 94% of bugs (known or unknown) worked out.  Still beating on it.  Please beat on it, too, and report bugs!  Thanks for the support!  Closing this one.
