### ISSUE TITLE
Arm Build - Pattern editor doesnt open

### ISSUE THREAD

**Issue by CarloCattano** [ahlstromcj/seq66#39]
Hi there . First and most important , thanks a lot for the effor required to maintain this project alive .
Ive recently discovered seq24 and the seq-quels. Im very inspired and hopefull with seq66.

Ive built it using the described methods on my raspberry pi . It all seems to be pretty alright, but when clicking on an empty pattern , I cant get the midi editor to display . Also the edit tab is empty no matter what .
I attach a log of the terminal and some screenshots .
Ive built it running on a raspberry pi 3B+ with [Patchbox OS](https://blokas.io/patchbox-os/docs/)

Im not very experienced in such complex projects but Im here to give you a hand as I can where needed .

I dream with the possibility of an easy midi looping environment that can run from terminal for performance time :-) 

![imagen](https://user-images.githubusercontent.com/17380530/107049371-4db9a980-67ca-11eb-9c09-f9f6575e6789.png)
![imagen](https://user-images.githubusercontent.com/17380530/107049432-5e6a1f80-67ca-11eb-8ee1-518db5a6b0a1.png)
[seq66Patchboxlog.txt](https://github.com/ahlstromcj/seq66/files/5933301/seq66Patchboxlog.txt)

**Comment by CarloCattano** [comment]
[[ BUILD INFO ]]
Built Feb  1 2021 10:21:39
  C++ version 201402
  App name: qseq66; type qt5; engine rtmidi
  Build OS: 'Linux 4.19.71-rt24-v7+ armv7l'
  Native JACK/ALSA (rtmidi)
  Event editor
  Follow progress bar
  Highlight empty patterns
  JACK support
  NSM (Non Session Manager) support
  Seq32 chord generator, LFO window, menu buttons, transpose, BPM
  Tap button, solid piano-roll grid, song performance recording
  Pattern coloring
  Pause support
  Save time-sig/tempo
  32-bit

Options are enabled/disabled via the configure script,
libseq66/include/seq66_features.h(pp), or the build-specific
seq66-config.h file in include/ or in include/qt/portmidi/

**Comment by ahlstromcj** [comment]
The Edit tab starts out empty (and disabled... however I might have checked in an experiment [branch "optimizing"] or even merged it to master (doh!)) If you're only working  in master, in a day or two I will make version 0.92.0 official in master. That will also include a full User's Manual. 

Anyway, to Edit in the tab, right-click on the desired pattern slot and select "Edit pattern in tab".  Another option is to "Edit pattern in window", which has more features (because the external pattern editor has more room to work with).

I have a Raspberry Pi that I can eventually set up to do any debugging for it.  Anyway, let me know if you work through this issue.  Thanks!

**Comment by CarloCattano** [comment]
I will double check the edit pattern in tab , but my build did not allow me to open the pattern window , and when right-clicking on the pattern slot and selecting edit pattern did not have an effect

**Comment by ahlstromcj** [comment]
When a pattern is empty, you have to right click and select New Pattern first.

For speed, I do a double-click on an empty pattern to create a new pattern,
then double-click again to open the new pattern in an external window (not in
the tab).  The tab pattern editor doesn't have as many features as the external
window.

If you still have issues, I will have to assemble my Pi kit and try to get it
to work.  I was actually saving it for my grandson and I to do together, but
he's too busy :-)

-------- Qwrtst 02:04 Fri 12 Feb      --------

>I will double check the edit pattern in tab , but my build did not allow me to open the pattern window , and when right-clicking on the pattern slot and selecting edit pattern did not have an effect
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/ahlstromcj/seq66/issues/39#issuecomment-778099853

-- 
Where do your SOCKS go when you lose them in th' WASHER?

**Comment by CarloCattano** [comment]
Hey there , Thanks for the hints . Im aware of the normal use and how to proceed . But its not happening .

Will keep trying and keeping an eye on this repo. I still could not find the ultimate tool to loop midi on the fly properly.
Thanks a lot for the efforts on seq66 !

**Comment by ahlstromcj** [comment]
Have you tried and gotten it to work on a regular laptop or desktop (Linux or
Windows)?  Still haven't gotten to hooking up the Pi here.

-------- Qwrtst 03:54 Tue 23 Feb      --------

>Hey there , Thanks for the hints . Im aware of the normal use and how to proceed . But its not happening .
>
>Will keep trying and keeping an eye on this repo. I still could not find the ultimate tool to loop midi on the fly properly.
>Thanks a lot for the efforts on seq66 !
>
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/ahlstromcj/seq66/issues/39#issuecomment-784147963

-- 
In any problem, if you find yourself doing an infinite amount of work,
the answer may be obtained by inspection.

**Comment by CarloCattano** [comment]
Unfortunately not . I only have a windows 10 laptop and the pi at the moment at disposal .
But I've installed and run seq24 and seq64 I believe in both systems and they "almost" do what I look for .
Im triying to switch from ableton Live based midi clips looping to an open source alternative . 
http://community.axoloti.com/t/raspberry-axoloti-thread/7100

:-)

**Comment by CarloCattano** [comment]
I never had much luck compiling open source projects in C++ till now . But one day Im going to get there

**Comment by ahlstromcj** [comment]
You can get a recent Windows build from:

https://github.com/ahlstromcj/sequencer64-packages/blob/master/seq66/0.92/seq66_setup_0.92.0.exe

You can't just right click on it, you have to get to the page with a download
button saying it is 25.9 Mb in size, and click the download button.  It's an
installer.

Actually building Seq66 on Windows is pretty straightforward.  
Install Qt Creator for Windows, selecting Mingw as the compiler.
See the "Qmake-based Install" section of the INSTALL file.
Also see the file data/readme.windows, as Microsoft is a bit tricky with
their MIDI Mapper.  Good luck!

-------- Qwrtst 04:28 Tue 23 Feb      --------

>I never had much luck compiling open source projects in C++ under windows till now . But one day Im going to get there
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/ahlstromcj/seq66/issues/39#issuecomment-784165927

-- 
A woman should have compassion.
		-- Kirk, "Catspaw", stardate 3018.2

**Comment by CarloCattano** [comment]
Hey thanks for the hints , I will try to build it on ubuntu to see if I get anything different . Using it on windows could be nice , but it would defeat the purpose on being portable as in a rpi3b+

**Comment by CarloCattano** [comment]
![image](https://user-images.githubusercontent.com/17380530/110250878-074c9b80-7f7e-11eb-8513-1e04311056a7.png)

Fresh build of 0.92.1 up and running very well on a Ubuntu Virtual machine , I will try to build again with the pi in the following days and double check .

The only added steps required for me as in the pi were:
```
sudo apt install qtbase5-dev
```

**Comment by CarloCattano** [comment]
Hello there !
A fresh build yesterday gave positive result . No issues so far , will try to practice a bit with it :-) 
You can consider the issue I was having closed
