### ISSUE TITLE
MIDI Input window doesn't handle large port counts

### ISSUE THREAD

**Issue by slightlynasty** [ahlstromcj/seq66#42]
In my studio setup I've got about 16 physical midi ports connected to the system, which appear twice when a2j is running. Currently the MIDI input window attempts to fit all the present ports in the one fixed-sized canvas area, regardless of how many there are, resulting in an unreadable mess as it tries to squeeze 32 checkboxes on top of each other. It seems like this should have scrolling added to allow for setups with these larger port counts.

Also, before I modified my midi driver to remove some unused virtual ports from one of my interfaces, I noticed that it seemed like output ports after number 32 weren't working, they could be selected in the drop-down but wouldn't output. Unfortunately I can't confirm this now because I've changed my setup around, but it might be worth looking into.

**Comment by ahlstromcj** [comment]
Heh, quite surprised someone's got this kind of setup with l'il ol' Seq66.
Anyway, I will look into either a vertical scroll window or a simple paging
spin button.

As for the 32 limit, that is hardwired.  How many In and Out ports do you
reckon are your maximum?

How does the app perform with all those ports?  Thanks!

-------- slightlynasty 00:49 Thu 04 Mar      --------

>In my studio setup I've got about 16 physical midi ports connected to the system, which appear twice when a2j is running. Currently the MIDI input window attempts to fit all the present ports in the one fixed-sized canvas area, regardless of how many there are, resulting in an unreadable mess as it tries to squeeze 32 checkboxes on top of each other. It seems like this should have scrolling added to allow for setups with these larger port counts.
>
>Also, before I modified my midi driver to remove some unused virtual ports from one of my interfaces, I noticed that it seemed like output ports after number 32 weren't working, they could be selected in the drop-down but wouldn't output. Unfortunately I can't confirm this now because I've changed my setup around, but it might be worth looking into.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/ahlstromcj/seq66/issues/42

-- 
The anger of a woman is the greatest evil with which you can threaten your
enemies.
		-- Bonnard

**Comment by slightlynasty** [comment]
Hey, thanks for the quick response! The ports do add up pretty quickly when you've got a combination of dedicated midi interfaces and external hardware that add their own over USB. I'm honestly generally only using a handful at any given time, maybe five or so, which obviously performs fine! It's just a convenience thing having everything permanently connected to its own dedicated port.

I just realised I can actually just disable the default jack midi ports and solely have the a2j instances appear, which solves the problem of them getting pushed past the 32 port limit. For some reason I assumed the normal jack alsa-sequencer driver had to be running for a2j to work, but obviously not.

**Comment by ahlstromcj** [comment]
This issue is fixed, and now part of the latest master, 0.92.1.
