### ISSUE TITLE
Extended MIDI Format / Type?

### ISSUE THREAD

**Issue by mxmilkiib** [ahlstromcj/seq66#43]
There was talk in #lad about the information in "21.2 Proprietary Track Format". Maybe it's better not to call it "Proprietary" but something like "Extended"? Other MIDI players/sequencers could utilise it.

Edit: easy manual link https://raw.githubusercontent.com/ahlstromcj/seq66/master/doc/seq66-user-manual.pdf

**Comment by ahlstromcj** [comment]
Can you point me to the discussion with a link?  Is that about the SeqSpec section?

http://www.shclemen.com/download/The%20Complete%20MIDI1.0%20Detailed%20Spec.pdf

Page 139 of that document discusses "Sequencer-Specific Meta-Event".  These are bytes:  FF 7F len data, where the first byte of data is the "manufacturer ID".  For Seq24/32/64/66, the format is "FF 7F 08 24 24 00 nn dd dd dd dd" where "24" is, I guess the de facto manufacturer's ID, "nn" is one of Seq66's features (e.g. mutegroups), and "dd..." is the data.  My understanding is that sequencers are supposed to ignore this item if they don't support it.  However, I know from testing the Windows Media Player cannot handle or ignore that.

Anyway, I will either create a dev manual or  a new section in the User's Manual that describes each of these "proprietary" items in enough detail to handle or ignore them.  Thanks!

**Comment by ahlstromcj** [comment]
Actually, section 21 of the user's manual already has a section on the MIDI format.  I will go through it and clarify it.  Thanks!

**Comment by ahlstromcj** [comment]
"Proprietary" was used internally to name the SeqSpec (sequencer-specific) code
in the MIDI file.  I've rectified the PDF to avoid using that loaded word.

-------- Milkii Brewster 08:11 Sun 07 Mar      --------

>There was talk in #lad about the information in "21.2 Proprietary Track Format". Maybe it's better not to call it "Proprietary" but something like "Extended"? Other MIDI players/sequencers could utilise it.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/ahlstromcj/seq66/issues/43

-- 
C'est magnifique, mais ce n'est pas l'Informatique.
		-- Bosquet [on seeing the IBM 4341]

**Comment by mxmilkiib** [comment]
Cool cool. I'm wondering also; if type 2 MIDI files are separate patterns playlisted into a song, but the documentation says type 1 with extra bits, though the experience of the app is like the type 2 format description, is it not then type 2 really? Or somewhere between the two?
