### ISSUE TITLE
data/Makefile.am does not respect DESTDIR

### ISSUE THREAD

**Issue by SpotlightKid** [ahlstromcj/seq66#45]
The target [install-data-local](https://github.com/ahlstromcj/seq66/blob/f2966c3d5cab05e8f6254a1bd8f1a45610d2f360/data/Makefile.am#L107) in `data/Makefile.am` does not respect the ``DESTDIR`` variable and thus fails with permission errors when make is called e.g. like this without sufficient privileges:

    make DESTDIR=/tmp/install-root install

This breaks distribution packaging, e.g. see here for the AUR package:

https://aur.archlinux.org/packages/seq66-git/#comment-801557

**Comment by ahlstromcj** [comment]
Just for speed, what would be the fix to the Makefile.am? Thanks!

-------- Christopher Arndt 08:42 Mon 12 Apr      --------

>The target [install-data-local](https://github.com/ahlstromcj/seq66/blob/f2966c3d5cab05e8f6254a1bd8f1a45610d2f360/data/Makefile.am#L107) in `data/Makefile.am` does not respect the ``DESTDIR`` variable and thus fails when make is called e.g. like this
>
>    make DESTDIR=/tmp/install-root install
>
>This breaks distribution packaging, e.g. see here for the AUR package:
>
>https://aur.archlinux.org/packages/seq66-git/#comment-801557
>
>
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/ahlstromcj/seq66/issues/45

-- 
If people drank ink instead of Schlitz, they'd be better off.
		-- Edward E. Hippensteel

[What brand of ink?  Ed.]

**Comment by SpotlightKid** [comment]
Sorry, I have no idea. I try to keep my sanity by not knowing anything about autotools.

**Comment by ahlstromcj** [comment]
This should be good in master 0.93.0 now.  The bug was in the category of a brain fart on my part :-(

**Comment by SpotlightKid** [comment]
Yes, all good now.

**Comment by SpotlightKid** [comment]
This happened again. Naive fix:

https://aur.archlinux.org/cgit/aur.git/tree/seq66-destdir.patch?h=seq66-git

**Comment by ahlstromcj** [comment]
That's odd.  I folded DESTDIR into these definitions in data/Makefile.am:

     datafolder = $(DESTDIR)$(seq66datadir)
     docfolder = $(DESTDIR)$(seq66docdir)

Will check it out when I get a chance.

-------- Christopher Arndt 22:21 Sun 23 Jan      --------

>This happened again. Naive fix:
>
>https://aur.archlinux.org/cgit/aur.git/tree/seq66-destdir.patch?h=seq66-git

**Comment by SpotlightKid** [comment]
But `datafolder` is not used for the `.desktop` and icon files. They go into `<prefix>/share/applications` resp. `<prefix>/share/icons`

**Comment by ahlstromcj** [comment]
Doh!

-------- Christopher Arndt 03:16 Mon 24 Jan      --------

>But `datafolder` is not used for the `.desktop` and icon files. They go into `<prefix>/share/applications` resp. `<prefix>/share/icons`
