### ISSUE TITLE
JACK-midi self-connections

### ISSUE THREAD

**Issue by moonshaadow** [ahlstromcj/seq66#48]
Hi there.

Why seq66 is self-connecting with every jack-midi port it founds, and is this really wanted ?
I like the way seq66 is providing inputs and outputs for everything.
But it could be a bit confusing in a large session with many elements, especially in a patchbay.

A possible solution could be to provide a midi output tab, just like the midi input one, and let users choose which ports they  want to be created and auto-connected.

**Comment by ahlstromcj** [comment]
There are two ways to work around your issue.  First, in the 'rc' file, look
for the "[manual-ports]" tag, and set it to "1" (the old name for "true").
You can also set the numbers if you want to.  This can also be set via the
command-line, and will be saved to the 'rc' file at Seq66 exit.  Once you're
running with that setup, you can then go to a patch-bay program (qjackctl) and
make the connections manually.  USB equipment might require running a2jmidid to
expose the USB ports to JACK.

Another way is to run Seq66, and go to the "MIDI Clocks" section of
Preferences.  There you can disable ports.  Exit, come back in, verify the
settings, and verify that it works as you expect.

Some bad naming, inherited from Seq24:

     1. "manual ports" should really be called "virtual ports.
     2. "MIDI Clocks" could also be called "MIDI Output"

Also check out the PDF user's manual.

Let me know here of any issues you encounter while doing this. Thanks for the
report!

-------- moonshaadow 01:07 Sun 25 Apr      --------

>Hi there.
>
>Why seq66 is self-connecting with every jack-midi port it founds, and is this really wanted ?
>I like the way seq66 is providing inputs and outputs for everything.
>But it could be a bit confusing in a large session with many elements, especially in a paychbay.
>
>A possible solution could be to provide a midi output tab, just like the midi input one, and let users choose which ports they  want to be created and auto-connected.
>
>
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/ahlstromcj/seq66/issues/48

-- 
inoculatte:
	To take coffee intravenously when you are running late.

**Comment by moonshaadow** [comment]
Thanks for the fast answer.
I didn't noticed the .rc [manual-ports] feature, it seems to work the way I want.

But I notice 2 possible bugs or unwanted features : 

-  With NSM and [manual ports] enabled, inputs ports aren't created when I load the session.
   Steps to reproduce : 
      * Create a NSM session with a jack-patch
      * Add qseq66
      * save and quit the session
      * change .rc file in the session folder to enable [manual-ports], then save the file
      * open your NSM session, use MIDI-input preference to create ports,  then make connections
      * save and reload the session.
    (I've used Ray-Session , but I guess it acts as others NSM managers)

- In Preferences view, switch to another tab than "MIDI Clock" prevents to go back to MIDI Clock tab until I restart Seq66

**Comment by ahlstromcj** [comment]
Thanks for the additional things to look at, especially for NSM/RaySession.

As for the MIDI Clock tab, that behavior drives me nuts.  I can find no reason
for it to happen.  However, there are a couple work-arounds:

     1. In the MIDI Clock tab, click near the bottom of the tab, on the
        underscore underneath the "C".  Or move around clicking until it works.

     2. Press Alt-C *twice*.

Like I said, weird stuff, drives me bsgfsck.  :-)

-------- moonshaadow 08:17 Sun 25 Apr      --------

>Thanks for the fast answer.
>I didn't noticed the .rc [manual-ports] feature, it seems to work the way I want.
>
>But I notice 2 possible bugs or unwanted features :
>
>-  With NSM and [manual ports] enabled, inputs ports aren't created when I load the session.
>   Steps to reproduce :
>      * Create a NSM session with a jack-patch
>      * Add qseq66
>      * save and quit the session
>      * change .rc file in the session folder to enable [manual-ports], then save the file
>      * open your NSM session, use MIDI-input preference to create ports,  then make connections
>      * save and reload the session.
>    (I've used Ray-Session , but I guess it acts as others NSM managers)
>
>- In Preferences view, switch to another tab than "MIDI Clock" prevents to go back to MIDI Clock tab until I restart Seq66
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/ahlstromcj/seq66/issues/48#issuecomment-826341101

-- 
"You're a creature of the night, Michael.  Wait'll Mom hears about this."
		-- from the movie "The Lost Boys"

**Comment by moonshaadow** [comment]
I notice another strange behavior with NSM, but maybe I should start another issue.
If [manual-ports] is off, then seq66 handles connections. IMO, this behavior should be disabled with NSM, because a session manager is supposed to store/restore the connections. I may be wrong, but I believe that the way other apps work with NSM.

**Comment by ahlstromcj** [comment]
Hmmmm.  NSM itself doesn't seem to handle that directly (see the messages
tallied in libsessions/src/nsm/nsmmessagesex.cpp).  However, it does provide
another app, jackpatch, that I think takes care of saving/restoring JACK
connections for a session.  Not sure it is documented all that well.  Imma gonna
look for documentation on it, and then figure out NSM's jackpatch.c code.
Not sure how it works.

I appreciate your airing stuff like this....  Keeps me on my toes and ultimately
improves the "product" (I hate that word).

I'm being followed by a moon shadow, moon shadow moon shadow :-)

-------- moonshaadow 08:42 Sun 25 Apr      --------

>I notice another strange behavior with NSM, but maybe I should start another issue.
>If [manual-ports] is off, then seq66 handles connections. IMO, this behavior should be disabled with NSM, because a session manager is supposed to store/restore the connections. I may be wrong, but I believe that the way other apps work with NSM.
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/ahlstromcj/seq66/issues/48#issuecomment-826344623

-- 
Conformity is the refuge of the unimaginative.
