### ISSUE TITLE
Unable to unmute loops after group learn

### ISSUE THREAD

**Issue by Tripayou** [ahlstromcj/seq66#49]
HI,
I found an issue with group learn. Loops learnt as muted in a mute group are mute blocked, pressing key or click on it has no effect. How to reproduce:
- open seq66
- open new project
- create loop 0, draw random notes then close editor
- do the same for loops 1 and 2
- unmute loops 0 and 1
- press learn key and assign a key, close success popup window
- unmute loop 2
- press play
- press mute key you assigned : the 3 loops are muted (I expected here loop 2 muted)
- press mute key again : loops 0 and 1 are armed, this is the correct state I saved and expected last step
- press loop 2 key or click on it : loop stay muted
- press stop : I can now unmute/mute loop 2 but if I press play the loop is automatically muted and blocked on start

I tried with several loops, all loops learnt as muted do the same

**Comment by ahlstromcj** [comment]
Man, this is a tough one.  It goes beyond what you observed.  My probes so far
have come up empty.  This might take awhile.  Thanks for the report!  I need
more wine to debug better!  :-)

-------- Tripayou 12:02 Mon 26 Apr      --------

>HI,
>I found an issue with group learn. Loops learnt as muted in a mute group are mute blocked, pressing key or click on it has no effect. How to reproduce:
>- open seq66
>- open new project
>- create loop 0, draw random notes then close editor
>- do the same for loops 1 and 2
>- unmute loops 0 and 1
>- press learn key and assign a key, close success popup window
>- unmute loop 2
>- press play
>- press mute key you assigned : the 3 loops are muted (I expected here loop 2 muted)
>- press mute key again : loops 0 and 1 are armed, this is the correct state I saved and expected last step
>- press loop 2 key or click on it : loop stay muted
>- press stop : I can now unmute/mute loop 2 but if I press play the loop is automatically muted and blocked on start
>
>I tried with several loops, all loops learnt as muted do the same
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/ahlstromcj/seq66/issues/49

-- 
GOOD-NIGHT, everybody ... Now I have to go administer FIRST-AID to my
pet LEISURE SUIT!!

**Comment by ahlstromcj** [comment]
I figured out that the song-mute flag was interfering with patterns outside the
mute-group that were enabled by the user.  Also added some flags to the 'mutes'
file to tweak the behavior.  Your steps have been basically tested, but
probably some more to test.  See the 'optimizing' branch.  As for the keystroke
issue, I really must think that one through thoroughly.  (Ain't English fun?)
Again, thanks so much for your exploration and reports!

-------- Tripayou 12:02 Mon 26 Apr      --------

>HI,
>I found an issue with group learn. Loops learnt as muted in a mute group are mute blocked, pressing key or click on it has no effect. How to reproduce:
>- open seq66
>- open new project
>- create loop 0, draw random notes then close editor
>- do the same for loops 1 and 2
>- unmute loops 0 and 1
>- press learn key and assign a key, close success popup window
>- unmute loop 2
>- press play
>- press mute key you assigned : the 3 loops are muted (I expected here loop 2 muted)
>- press mute key again : loops 0 and 1 are armed, this is the correct state I saved and expected last step
>- press loop 2 key or click on it : loop stay muted
>- press stop : I can now unmute/mute loop 2 but if I press play the loop is automatically muted and blocked on start
>
>I tried with several loops, all loops learnt as muted do the same
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/ahlstromcj/seq66/issues/49

-- 
Any father who thinks he's all important should remind himself that this
country honors fathers only one day a year while pickles get a whole week.

**Comment by Tripayou** [comment]
Good work, loops are not mute blocked anymore after group learn, and pressing group key toggles loops in their correct state on first press. Pressing group key when loops are in memorised state  mute all loops.
