### ISSUE TITLE
"Resume playback of notes on sequence toggle" option doesn't work/save

### ISSUE THREAD

**Issue by mxmilkiib** [ahlstromcj/seq66#5]
It doesn't create a note on event when there is a note that would have been playing, and in the options dialog it resets to unchecked when the app is started next time.

**Comment by ahlstromcj** [comment]
This turned out to be a feature I had not finished implementing.  Derived from code in Kepler34.  I added infrastructure to save the setting in the qseq66.usr file when added, and added a missing call to the triggers::play() function.  Not yet tested, but wanted to get the code safely archived.

**Comment by mxmilkiib** [comment]
Have just tried with 8668d5e but it's not saving the option nor 'restarting' a long note on reactivating the pattern.

**Comment by ahlstromcj** [comment]
Will look into it soon. Haven't had a change to test it yet.  Thanks!

-------- Milkii Brewster 14:31 Sat 20 Jun      --------

>Have just tried with 8668d5e but it's not saving the option nor 'restarting' a long note on reactivating the pattern.
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/ahlstromcj/seq66/issues/5#issuecomment-647047683

-- 
Outside of a dog, a book is man's best friend.  Inside of a dog, it is too
dark to read.

**Comment by mxmilkiib** [comment]
The option is now saving properly, but notes do not restart.

**Comment by ahlstromcj** [comment]
Found a lot of issues while trying to test this fix, that is why it took so
long!  Here is how to test it:

1. Run "./Seq66qt5/qseq66 -b 3 contrib/midi/2B-test.midi".  The "-b 3" option can be dropped or altered to whatever gets you sound from your setup.
2. Set Edit / Preferences / Play Options / Resume playback at sequence toggle to "checked".
3. Set to Song mode.
4. Open the Song tab and note the third pattern.  It has long notes. Verify the song plays.
5. Click in the performance roll to give it focus.  Use the "." (period) key to start and pause the playback at various points, and note that the proper notes resume.
6. Now select Live mode and open pattern 2 (third pattern) in an external editor.
7. Click in the seq roll to give it focus.  Use the "." (period) key to start and pause the playback at various points, and note that the proper notes resume.

**Comment by mxmilkiib** [comment]
[Here](https://www.youtube.com/watch?v=WLVrHvT802E) is a video of my trying with my project file, there is some output but it's not working right. The part where it jumps back to the beginning is when I pressed '.'

**Comment by ahlstromcj** [comment]
Okay, will look into it. In the meantime, does the test scenario in my
comment work for you? Thanks, your input is appreciated!

**Comment by mxmilkiib** [comment]
No, it doesn't work. Also, that file is weird; on every loop the tempo changes to be fast again, no matter how slow I make it whilst it's playing before it loops.

**Comment by ahlstromcj** [comment]
I see what you meant.  It was actually beyond the scope of kepler34's implementation of resume notes.  But I was able to extend it to simple sequence toggling.  And I updated the configuration description to better reflect that.  So now, if you have the option set and toggle just a single pattern, it will resume the Note Ons for that pattern.  If you do a pause or stop of the whole playback, it will resume the notes of all sequences if applicable.  Anyway, interim check-in, let me know if I have fulfilled your expectations!

**Comment by mxmilkiib** [comment]
Cheers :) Hmm, I'm getting a build error now, maybe I have done something to my system?

```
...
checking for ALSA LDFLAGS...  -lasound -lm -ldl -lpthread -lasound -lm -ldl -lpthread
checking for libasound headers version >= 0.9.0... found.
checking for snd_ctl_open in -lasound... (cached) yes
checking for X... libraries , headers 
checking for gethostbyname... yes
checking for connect... yes
checking for remove... yes
checking for shmat... yes
checking for IceConnectionNumber in -lICE... yes
checking for Qt... yes:
    QT_CXXFLAGS=-pipe -D_FORTIFY_SOURCE=2 -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -Wall -Wextra -D_REENTRANT -fPIC -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I. -isystem /usr/include/qt -isystem /usr/include/qt/QtWidgets -isystem /usr/include/qt/QtGui -isystem /usr/include/qt/QtCore -I. -I/usr/lib/qt/mkspecs/linux-g++ 
    QT_DIR=/usr/lib
    QT_LIBS=/usr/lib/libQt5Widgets.so /usr/lib/libQt5Gui.so /usr/lib/libQt5Core.so -lGL -lpthread  
    QT_MOC=/usr/bin/moc
    QT_RCC=/usr/bin/rcc
    QT_UIC=/usr/bin/uic
    QT_LRELEASE=/usr/bin/lrelease
    QT_LUPDATE=/usr/bin/lupdate
checking correct functioning of Qt installation... failure
configure: error: Failed to find matching components of a complete
                  Qt installation. Try using more options,
                  see ./configure --help.
==> ERROR: A failure occurred in build().
```

**Comment by ahlstromcj** [comment]
Try this sequence if you haven't already:

$ ./bootstrap --full-clean
$ ./bootstrap -er

If that works then the usual

$ make &> make.log

The only issue I have is that, on my Debian Sid laptop, building a debug version fails at the end with trying to link in one Qt static library.  Weird, never have figured that out.

You can also go to the seq66 directory then:

$ cd ..
$ mkdir shadow-seq66
$ cd shadow-seq66
$ qmake -makefile -recursive "CONFIG += rtmidi" ../seq66/seq66.pro
$ make &> make.log

You can also use "CONFIG += debug rtmidi".   I had to upgrade the Qt setup so I could debug on this laptop.

**Comment by mxmilkiib** [comment]
Thank you. I'll be out of town for a few days and will check things out in my return

**Comment by mxmilkiib** [comment]
Back home now. Ah, it's #2, resolved by adding a gambas3-gb-qt5-opengl dependency.

I'm now stuck on a similar problem; https://gist.github.com/mxmilkiib/df6eae06afb6d5de98e155aea3a51265

**Comment by mxmilkiib** [comment]
Looking further today, I guess there is another Qt related dependency to add for an Arch build? I tried looking at the INSTALL file but the DEPENDENCY information but I found the information there a bit too atomic to figure out the missing Arch package.

**Comment by ahlstromcj** [comment]
Are you running Arch?

**Comment by mxmilkiib** [comment]
Yes.

I realised the shadow instructions were working, but not the PKGBUILD, so I've partly updated the PKGBUILD but I've got the package() phase left to update. This is what I have so far

```
_pkgname=seq66
pkgname="${_pkgname}-git"
pkgver=0.90.4.r186.f4f1619
pkgrel=1
pkgdesc="A live-looping sequencer with an interface similar to hardware sequencers"
arch=('i686' 'x86_64')
url="https://github.com/ahlstromcj/seq66"
license=('GPL2')
depends=('jack' 'qt5-base' 'gambas3-gb-qt5-opengl')
makedepends=('git')
groups=('pro-audio')
provides=("${_pkgname}" "${_pkgname}=${pkgver//.r*/}")
conflicts=("${_pkgname}")
source=("${_pkgname}::git+https://github.com/ahlstromcj/${_pkgname}.git#branch=optimizing")
md5sums=('SKIP')

pkgver() {
  cd "${srcdir}/${_pkgname}"
  local ver=$(tail -n 1 VERSION)
  # replace alpha chars with a dot
  echo "$ver.r$(git rev-list --count HEAD).$(git rev-parse --short HEAD)"
}

build() {
  cd "${srcdir}/${_pkgname}"
  mkdir -p build
  cd build
  qmake -makefile -recursive "CONFIG += rtmidi" ../seq66.pro
  make
}

package() {
  cd "${srcdir}/${_pkgname}"
  make DESTDIR="${pkgdir}/" install
}
```

**Comment by mxmilkiib** [comment]
So I gave up trying to fix the packaging and just tested for this issue, and it works, many thanks :)
