### ISSUE TITLE
White text on Yellow is unreadable

### ISSUE THREAD

**Issue by unfa** [ahlstromcj/seq66#50]
Hey!

I've recently updated Seq66 and I want to do some live music with it on my next livestream.

On my system (Manajro KDE, using Breeze-dark theme)  the default pattern look is Yellow BG and White text - this is quite unreadable.

Is it possible to somehow make Yellow BG use black text instead? 

Thanks!

**Comment by ahlstromcj** [comment]
Between the .palette file and Qt style-sheets, the appearance of Seq66 is almost fully configurable.
