### ISSUE TITLE
MIDI CC sequencing

### ISSUE THREAD

**Issue by oparisy** [ahlstromcj/seq66#53]
I'm not sure if this is the proper vocabulary, but can seq66 be used to "sequence" and output MIDI CC (Continuous Controllers) messages?

As an example, so as to be able to control and alter some synth parameters in the course of a pattern play.

I guess DAWs typically call this "automation"?

**Comment by ahlstromcj** [comment]
Seq66 can read CC's from a MIDI file and play them back, and also display them.  They can be edited to some extent as well.  By default, Note Ons are shown in the grey data pane, by other events can be chosen to be viewed and then modified.

Some rudimentary editing can be done in the Events tab as well.

As for automation,  Seq66 supports both incoming MIDI to control many aspects of the application (including muting and mute groups), and outgoing MIDI to display the status (e.g. on a Novation LaunchPad).

The idea of Seq66 being able to adjust CCs on the fly manually is cool, but I have to think a lot about how that would work.

In the meantime, you can use your powerful MIDI controller and the MIDI Thru that Seq66 supports to forward the controls e.g. to a software synth.

Go through the User Manual (doc/seq66-user-manual.pdf) and see if what you need is covered.  Check out data/linux/qseq66-lp-mini.ctrl as well. Also examine the dataIf not covered, report back with what specific use-case you think is missing.  Thanks!

-------- oparisy 13:03 Wed 05 May      --------

>I'm not sure if this is the proper vocabulary, but can seq66 be used to "sequence" and output MIDI CC (Continuous Controllers) messages?
>
>As an example, so as to be able to control and alter some synth parameters in the course of a pattern play.
>
>I guess DAWs typically call this "automation"?
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/ahlstromcj/seq66/issues/53

-- 
"...proper attention to Earthly needs of the poor, the depressed and the
downtrodden, would naturally evolve from dynamic, articulate, spirited
awareness of the great goals for Man and the society he conspired to erect."
		-- David Baker, paraphrasing Harold Urey, in "The History of Manned Space Flight"
