### ISSUE TITLE
MIDI Control File - Different Channels 

### ISSUE THREAD

**Issue by alpacalife** [ahlstromcj/seq66#55]
Been creating a .ctrl file for an Akai APC40 because I was a bit bored. It has an 5x8 pad. It is detecting input but I am having some issues with the pad maps. 

Each column of the pad sends on a different channel, but the same notes. I configured the ctrl file with this:
```
 0 "1"           [ 0 0x90  53   1 127 ] [ 0 0x00   0   0   0 ] [ 0 0x00   0   0   0 ] # Loop 0
 1 "q"           [ 0 0x90  54   1 127 ] [ 0 0x00   0   0   0 ] [ 0 0x00   0   0   0 ] # Loop 1
 2 "a"           [ 0 0x90  55   1 127 ] [ 0 0x00   0   0   0 ] [ 0 0x00   0   0   0 ] # Loop 2
 3 "z"           [ 0 0x90  56   1 127 ] [ 0 0x00   0   0   0 ] [ 0 0x00   0   0   0 ] # Loop 3
 4 "2"           [ 0 0x91  53   1 127 ] [ 0 0x00   0   0   0 ] [ 0 0x00   0   0   0 ] # Loop 4
 5 "w"           [ 0 0x91  54   1 127 ] [ 0 0x00   0   0   0 ] [ 0 0x00   0   0   0 ] # Loop 5
 6 "s"           [ 0 0x91  55   1 127 ] [ 0 0x00   0   0   0 ] [ 0 0x00   0   0   0 ] # Loop 6
 7 "x"           [ 0 0x91  56   1 127 ] [ 0 0x00   0   0   0 ] [ 0 0x00   0   0   0 ] # Loop 7
 8 "3"           [ 0 0x92  53   1 127 ] [ 0 0x00   0   0   0 ] [ 0 0x00   0   0   0 ] # Loop 8
 9 "e"           [ 0 0x92  54   1 127 ] [ 0 0x00   0   0   0 ] [ 0 0x00   0   0   0 ] # Loop 9
10 "d"           [ 0 0x92  55   1 127 ] [ 0 0x00   0   0   0 ] [ 0 0x00   0   0   0 ] # Loop 10
11 "c"           [ 0 0x92  56   1 127 ] [ 0 0x00   0   0   0 ] [ 0 0x00   0   0   0 ] # Loop 11
12 "4"           [ 0 0x93  53   1 127 ] [ 0 0x00   0   0   0 ] [ 0 0x00   0   0   0 ] # Loop 12
13 "r"           [ 0 0x93  54   1 127 ] [ 0 0x00   0   0   0 ] [ 0 0x00   0   0   0 ] # Loop 13
14 "f"           [ 0 0x93  55   1 127 ] [ 0 0x00   0   0   0 ] [ 0 0x00   0   0   0 ] # Loop 14
15 "v"           [ 0 0x93  56   1 127 ] [ 0 0x00   0   0   0 ] [ 0 0x00   0   0   0 ] # Loop 15
16 "5"           [ 0 0x94  53   1 127 ] [ 0 0x00   0   0   0 ] [ 0 0x00   0   0   0 ] # Loop 16
17 "t"           [ 0 0x94  54   1 127 ] [ 0 0x00   0   0   0 ] [ 0 0x00   0   0   0 ] # Loop 17
18 "g"           [ 0 0x94  55   1 127 ] [ 0 0x00   0   0   0 ] [ 0 0x00   0   0   0 ] # Loop 18
19 "b"           [ 0 0x94  56   1 127 ] [ 0 0x00   0   0   0 ] [ 0 0x00   0   0   0 ] # Loop 19
20 "6"           [ 0 0x95  53   1 127 ] [ 0 0x00   0   0   0 ] [ 0 0x00   0   0   0 ] # Loop 20
21 "y"           [ 0 0x95  54   1 127 ] [ 0 0x00   0   0   0 ] [ 0 0x00   0   0   0 ] # Loop 21
22 "h"           [ 0 0x95  55   1 127 ] [ 0 0x00   0   0   0 ] [ 0 0x00   0   0   0 ] # Loop 22
23 "n"           [ 0 0x95  56   1 127 ] [ 0 0x00   0   0   0 ] [ 0 0x00   0   0   0 ] # Loop 23
24 "7"           [ 0 0x96  53   1 127 ] [ 0 0x00   0   0   0 ] [ 0 0x00   0   0   0 ] # Loop 24
25 "u"           [ 0 0x96  54   1 127 ] [ 0 0x00   0   0   0 ] [ 0 0x00   0   0   0 ] # Loop 25
26 "j"           [ 0 0x96  55   1 127 ] [ 0 0x00   0   0   0 ] [ 0 0x00   0   0   0 ] # Loop 26
27 "m"           [ 0 0x96  56   1 127 ] [ 0 0x00   0   0   0 ] [ 0 0x00   0   0   0 ] # Loop 27
28 "8"           [ 0 0x97  53   1 127 ] [ 0 0x00   0   0   0 ] [ 0 0x00   0   0   0 ] # Loop 28
29 "i"           [ 0 0x97  54   1 127 ] [ 0 0x00   0   0   0 ] [ 0 0x00   0   0   0 ] # Loop 29
30 "k"           [ 0 0x97  55   1 127 ] [ 0 0x00   0   0   0 ] [ 0 0x00   0   0   0 ] # Loop 30
31 ","           [ 0 0x97  56   1 127 ] [ 0 0x00   0   0   0 ] [ 0 0x00   0   0   0 ] # Loop 31
```

- Column 1 is toggling on Ch1 Note On. This works as expected. 
- Column 2 is toggling on Ch2 Note On. This is detected by seq66 just fine, but it is triggering the pattern in Column 1. So pressing 4 triggers 0 to arm/mute. 
- Other columns do the same as column 2.

Now I may be just doing it wrong as well, but I think I read the documentation right! I haven't got to the light midi out or mute groups until I get this part working.

**Comment by ahlstromcj** [comment]
Sounds like seq66 is stripping (zeroing) the channel.  Time for some debugging.  All I have is a LaunchPad Mini,
but I can step throught the code and spot the problem I think.  Thanks for the report!

-------- Mark Tustin 00:49 Fri 06 Aug      --------

>Been creating a .ctrl file for an Akai APC40 because I was a bit bored. It has an 5x8 pad. It is detecting input but I am having some issues with the pad maps.
>
>Each column of the pad sends on a different channel, but the same notes. I configured the ctrl file with this:
>```
> 0 "1"           [ 0 0x90  53   1 127 ] [ 0 0x00   0   0   0 ] [ 0 0x00   0   0   0 ] # Loop 0
> 1 "q"           [ 0 0x90  54   1 127 ] [ 0 0x00   0   0   0 ] [ 0 0x00   0   0   0 ] # Loop 1
> 2 "a"           [ 0 0x90  55   1 127 ] [ 0 0x00   0   0   0 ] [ 0 0x00   0   0   0 ] # Loop 2
> 3 "z"           [ 0 0x90  56   1 127 ] [ 0 0x00   0   0   0 ] [ 0 0x00   0   0   0 ] # Loop 3
> 4 "2"           [ 0 0x91  53   1 127 ] [ 0 0x00   0   0   0 ] [ 0 0x00   0   0   0 ] # Loop 4
> 5 "w"           [ 0 0x91  54   1 127 ] [ 0 0x00   0   0   0 ] [ 0 0x00   0   0   0 ] # Loop 5
> 6 "s"           [ 0 0x91  55   1 127 ] [ 0 0x00   0   0   0 ] [ 0 0x00   0   0   0 ] # Loop 6
> 7 "x"           [ 0 0x91  56   1 127 ] [ 0 0x00   0   0   0 ] [ 0 0x00   0   0   0 ] # Loop 7
> 8 "3"           [ 0 0x92  53   1 127 ] [ 0 0x00   0   0   0 ] [ 0 0x00   0   0   0 ] # Loop 8
> 9 "e"           [ 0 0x92  54   1 127 ] [ 0 0x00   0   0   0 ] [ 0 0x00   0   0   0 ] # Loop 9
>10 "d"           [ 0 0x92  55   1 127 ] [ 0 0x00   0   0   0 ] [ 0 0x00   0   0   0 ] # Loop 10
>11 "c"           [ 0 0x92  56   1 127 ] [ 0 0x00   0   0   0 ] [ 0 0x00   0   0   0 ] # Loop 11
>12 "4"           [ 0 0x93  53   1 127 ] [ 0 0x00   0   0   0 ] [ 0 0x00   0   0   0 ] # Loop 12
>13 "r"           [ 0 0x93  54   1 127 ] [ 0 0x00   0   0   0 ] [ 0 0x00   0   0   0 ] # Loop 13
>14 "f"           [ 0 0x93  55   1 127 ] [ 0 0x00   0   0   0 ] [ 0 0x00   0   0   0 ] # Loop 14
>15 "v"           [ 0 0x93  56   1 127 ] [ 0 0x00   0   0   0 ] [ 0 0x00   0   0   0 ] # Loop 15
>16 "5"           [ 0 0x94  53   1 127 ] [ 0 0x00   0   0   0 ] [ 0 0x00   0   0   0 ] # Loop 16
>17 "t"           [ 0 0x94  54   1 127 ] [ 0 0x00   0   0   0 ] [ 0 0x00   0   0   0 ] # Loop 17
>18 "g"           [ 0 0x94  55   1 127 ] [ 0 0x00   0   0   0 ] [ 0 0x00   0   0   0 ] # Loop 18
>19 "b"           [ 0 0x94  56   1 127 ] [ 0 0x00   0   0   0 ] [ 0 0x00   0   0   0 ] # Loop 19
>20 "6"           [ 0 0x95  53   1 127 ] [ 0 0x00   0   0   0 ] [ 0 0x00   0   0   0 ] # Loop 20
>21 "y"           [ 0 0x95  54   1 127 ] [ 0 0x00   0   0   0 ] [ 0 0x00   0   0   0 ] # Loop 21
>22 "h"           [ 0 0x95  55   1 127 ] [ 0 0x00   0   0   0 ] [ 0 0x00   0   0   0 ] # Loop 22
>23 "n"           [ 0 0x95  56   1 127 ] [ 0 0x00   0   0   0 ] [ 0 0x00   0   0   0 ] # Loop 23
>24 "7"           [ 0 0x96  53   1 127 ] [ 0 0x00   0   0   0 ] [ 0 0x00   0   0   0 ] # Loop 24
>25 "u"           [ 0 0x96  54   1 127 ] [ 0 0x00   0   0   0 ] [ 0 0x00   0   0   0 ] # Loop 25
>26 "j"           [ 0 0x96  55   1 127 ] [ 0 0x00   0   0   0 ] [ 0 0x00   0   0   0 ] # Loop 26
>27 "m"           [ 0 0x96  56   1 127 ] [ 0 0x00   0   0   0 ] [ 0 0x00   0   0   0 ] # Loop 27
>28 "8"           [ 0 0x97  53   1 127 ] [ 0 0x00   0   0   0 ] [ 0 0x00   0   0   0 ] # Loop 28
>29 "i"           [ 0 0x97  54   1 127 ] [ 0 0x00   0   0   0 ] [ 0 0x00   0   0   0 ] # Loop 29
>30 "k"           [ 0 0x97  55   1 127 ] [ 0 0x00   0   0   0 ] [ 0 0x00   0   0   0 ] # Loop 30
>31 ","           [ 0 0x97  56   1 127 ] [ 0 0x00   0   0   0 ] [ 0 0x00   0   0   0 ] # Loop 31
>```
>
>- Column 1 is toggling on Ch1 Note On. This works as expected.
>- Column 2 is toggling on Ch2 Note On. This is detected by seq66 just fine, but it is triggering the pattern in Column 1. So pressing 4 triggers 0 to arm/mute.
>- Other columns do the same as column 2.
>
>Now I may be just doing it wrong as well, but I think I read the documentation right! I haven't got to the light midi out or mute groups until I get this part working.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/ahlstromcj/seq66/issues/55

-- 
Too much is just enough.
		-- Mark Twain, on whiskey

**Comment by ahlstromcj** [comment]
I found this issue in JACK handling and have, I think, fixed it.  If you're
using JACK, check out the "optimizing" branch and build it and see if it works.
If not using JACK, let me know so I can continue debugging.  I will test more
thorough in a bit, but don't have time at the moment.  Also found a
long-standing bug in the "portmidi" (Linux/Windows) handling of incoming events
from multiple devices.  Embarrassing!  Your bug report has been very valuable!

-------- Mark Tustin 00:49 Fri 06 Aug      --------

>Been creating a .ctrl file for an Akai APC40 because I was a bit bored. It has an 5x8 pad. It is detecting input but I am having some issues with the pad maps.
>
>Each column of the pad sends on a different channel, but the same notes. I configured the ctrl file with this:
>```
> 0 "1"           [ 0 0x90  53   1 127 ] [ 0 0x00   0   0   0 ] [ 0 0x00   0   0   0 ] # Loop 0
> 1 "q"           [ 0 0x90  54   1 127 ] [ 0 0x00   0   0   0 ] [ 0 0x00   0   0   0 ] # Loop 1
> 2 "a"           [ 0 0x90  55   1 127 ] [ 0 0x00   0   0   0 ] [ 0 0x00   0   0   0 ] # Loop 2
> 3 "z"           [ 0 0x90  56   1 127 ] [ 0 0x00   0   0   0 ] [ 0 0x00   0   0   0 ] # Loop 3
> 4 "2"           [ 0 0x91  53   1 127 ] [ 0 0x00   0   0   0 ] [ 0 0x00   0   0   0 ] # Loop 4
> 5 "w"           [ 0 0x91  54   1 127 ] [ 0 0x00   0   0   0 ] [ 0 0x00   0   0   0 ] # Loop 5
> 6 "s"           [ 0 0x91  55   1 127 ] [ 0 0x00   0   0   0 ] [ 0 0x00   0   0   0 ] # Loop 6
> 7 "x"           [ 0 0x91  56   1 127 ] [ 0 0x00   0   0   0 ] [ 0 0x00   0   0   0 ] # Loop 7
> 8 "3"           [ 0 0x92  53   1 127 ] [ 0 0x00   0   0   0 ] [ 0 0x00   0   0   0 ] # Loop 8
> 9 "e"           [ 0 0x92  54   1 127 ] [ 0 0x00   0   0   0 ] [ 0 0x00   0   0   0 ] # Loop 9
>10 "d"           [ 0 0x92  55   1 127 ] [ 0 0x00   0   0   0 ] [ 0 0x00   0   0   0 ] # Loop 10
>11 "c"           [ 0 0x92  56   1 127 ] [ 0 0x00   0   0   0 ] [ 0 0x00   0   0   0 ] # Loop 11
>12 "4"           [ 0 0x93  53   1 127 ] [ 0 0x00   0   0   0 ] [ 0 0x00   0   0   0 ] # Loop 12
>13 "r"           [ 0 0x93  54   1 127 ] [ 0 0x00   0   0   0 ] [ 0 0x00   0   0   0 ] # Loop 13
>14 "f"           [ 0 0x93  55   1 127 ] [ 0 0x00   0   0   0 ] [ 0 0x00   0   0   0 ] # Loop 14
>15 "v"           [ 0 0x93  56   1 127 ] [ 0 0x00   0   0   0 ] [ 0 0x00   0   0   0 ] # Loop 15
>16 "5"           [ 0 0x94  53   1 127 ] [ 0 0x00   0   0   0 ] [ 0 0x00   0   0   0 ] # Loop 16
>17 "t"           [ 0 0x94  54   1 127 ] [ 0 0x00   0   0   0 ] [ 0 0x00   0   0   0 ] # Loop 17
>18 "g"           [ 0 0x94  55   1 127 ] [ 0 0x00   0   0   0 ] [ 0 0x00   0   0   0 ] # Loop 18
>19 "b"           [ 0 0x94  56   1 127 ] [ 0 0x00   0   0   0 ] [ 0 0x00   0   0   0 ] # Loop 19
>20 "6"           [ 0 0x95  53   1 127 ] [ 0 0x00   0   0   0 ] [ 0 0x00   0   0   0 ] # Loop 20
>21 "y"           [ 0 0x95  54   1 127 ] [ 0 0x00   0   0   0 ] [ 0 0x00   0   0   0 ] # Loop 21
>22 "h"           [ 0 0x95  55   1 127 ] [ 0 0x00   0   0   0 ] [ 0 0x00   0   0   0 ] # Loop 22
>23 "n"           [ 0 0x95  56   1 127 ] [ 0 0x00   0   0   0 ] [ 0 0x00   0   0   0 ] # Loop 23
>24 "7"           [ 0 0x96  53   1 127 ] [ 0 0x00   0   0   0 ] [ 0 0x00   0   0   0 ] # Loop 24
>25 "u"           [ 0 0x96  54   1 127 ] [ 0 0x00   0   0   0 ] [ 0 0x00   0   0   0 ] # Loop 25
>26 "j"           [ 0 0x96  55   1 127 ] [ 0 0x00   0   0   0 ] [ 0 0x00   0   0   0 ] # Loop 26
>27 "m"           [ 0 0x96  56   1 127 ] [ 0 0x00   0   0   0 ] [ 0 0x00   0   0   0 ] # Loop 27
>28 "8"           [ 0 0x97  53   1 127 ] [ 0 0x00   0   0   0 ] [ 0 0x00   0   0   0 ] # Loop 28
>29 "i"           [ 0 0x97  54   1 127 ] [ 0 0x00   0   0   0 ] [ 0 0x00   0   0   0 ] # Loop 29
>30 "k"           [ 0 0x97  55   1 127 ] [ 0 0x00   0   0   0 ] [ 0 0x00   0   0   0 ] # Loop 30
>31 ","           [ 0 0x97  56   1 127 ] [ 0 0x00   0   0   0 ] [ 0 0x00   0   0   0 ] # Loop 31
>```
>
>- Column 1 is toggling on Ch1 Note On. This works as expected.
>- Column 2 is toggling on Ch2 Note On. This is detected by seq66 just fine, but it is triggering the pattern in Column 1. So pressing 4 triggers 0 to arm/mute.
>- Other columns do the same as column 2.
>
>Now I may be just doing it wrong as well, but I think I read the documentation right! I haven't got to the light midi out or mute groups until I get this part working.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/ahlstromcj/seq66/issues/55

-- 
Equal bytes for women.

**Comment by alpacalife** [comment]
Built from the optimized branch and it is working as expected now. So that issue seems solved. 

Glad the report was valuable!

**Comment by ahlstromcj** [comment]
Indeed!  Now I am working through some other wrinkles with Seq66's channel
handling, specifically the "Free" channel.  Thanks again!

-------- Mark Tustin 21:43 Sun 08 Aug      --------

>Built from the optimized branch and it is working as expected now. So that issue seems solved.
>
>Glad the report was valuable!
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/ahlstromcj/seq66/issues/55#issuecomment-894946520

-- 
Actually, what I'd like is a little toy spaceship!!
