### ISSUE TITLE
Build fails without lash.h

### ISSUE THREAD

**Issue by mxmilkiib** [ahlstromcj/seq66#6]
I don't use LASH (I prefer NSM, though I know at least one person who does use it)

![image](https://user-images.githubusercontent.com/108225/86637792-17b30d80-bfce-11ea-99df-53fd3c704895.png)

Edit: [the rest of the log](https://gist.github.com/mxmilkiib/50298624018a8c5533b701f4a4e16dab)

**Comment by ahlstromcj** [comment]
I made LASH disabled in configure.ac by default.  I also tested that build
after removing all traces of LASH packages, and it works.  Let me know of any
issues. Thanks!

-------- Milkii Brewster 13:19 Mon 06 Jul      --------

>I don't use LASH (I prefer NSM, though I know at least one person who does use it)
>
>![image](https://user-images.githubusercontent.com/108225/86637792-17b30d80-bfce-11ea-99df-53fd3c704895.png)
>
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/ahlstromcj/seq66/issues/6

-- 
According to all the latest reports, there was no truth in any of the
earlier reports.

**Comment by mxmilkiib** [comment]
Build completes without lash installed now :)
