### ISSUE TITLE
GUI option to disable auto midi port creation/connection?

### ISSUE THREAD

**Issue by mxmilkiib** [ahlstromcj/seq66#60]
More of a closed question/proposal compared to the openness of #48 regarding the awkward auto-creation of MIDI output ports for every MIDI input port the JACK graph and the apparent attempted creation of connections between them.

Having to go edit config files to switch this up makes seq66 hard and annoying to use.

An option in the GUI to change this would be très handy!

![2021-10-11_03-28_seq66_autoports](https://user-images.githubusercontent.com/108225/137980473-3bbbce5c-17ac-4ff4-b366-261e87023130.png)

**Comment by ahlstromcj** [comment]
JACK auto-connect can be disable in Edit / Preferences / JACK (and the 'rc' file).

**Comment by mxmilkiib** [comment]
Thanks!
