### ISSUE TITLE
If under NSM, append terminal log lines with [seq66]?

### ISSUE THREAD

**Issue by mxmilkiib** [ahlstromcj/seq66#61]
I'm running Agordejo in a terminal. There's a lot of output from all the apps launched there, and it would be handy if, there is an NSM session, log lines could start with [seq66] or [qseq66]. 

Similar issue; https://github.com/falkTX/Carla/issues/1498

**Comment by ahlstromcj** [comment]
I had been mulling that over, and your report has pushed me over the edge.
I have implemented it in a manner similar to NSM, and will probably make it
official in version 0.97.1 by COB today("close of business", for those in the
business business, heh heh.)

-------- Milkii Brewster 18:23 Tue 19 Oct      --------

>I'm running Agordejo in a terminal. There's a lot of output from all the apps launched there, and it would be handy if, there is an NSM session, log lines could start with [seq66] or [qseq66].
>
>Similar issue; https://github.com/falkTX/Carla/issues/1498
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/ahlstromcj/seq66/issues/61

-- 
A kind of Batman of contemporary letters.
		-- Philip Larkin on Anthony Burgess
