### ISSUE TITLE
Compile issues on Raspbian

### ISSUE THREAD

**Issue by seanrieger** [ahlstromcj/seq66#70]
Is there a precompiled package for Raspbian? I am struggling to compile this at all. I am a complete novice at compiling source code, but when I run ./configure in the project root I get the error "configure: error: cannot find install-sh, install.sh, or shtool in aux-files "."/aux-files" I tried also running the reconf as suggested, but with that I just get more errors with that. 

pi@raspberrypi:~/Desktop/seq66-0.97.2.1/contrib/scripts $ ./reconf
libtoolize: putting auxiliary files in '.'.
libtoolize: linking file './ltmain.sh'
aclocal: error: 'configure.ac' is required
autoheader: 'configure.ac' or 'configure.in' is required
automake: error: 'configure.ac' is required
autoconf: error: no input file

**Comment by ahlstromcj** [comment]
People have gotten it to compile, but I still don't have my Pi unboxed.  Try
running "contrib/scripts/reconf" from the seq66-0.97.2 directory.

Also read through the INSTALL file.  After all DEPENDENCIES are ready you
can then run "./bootstrap --full-clean" then "./bootstrap -er" to set up for
release mode, then "make", etc.

There's also a link in INSTALL to someone who used "Muon" to install it on a
Pi.  Good luck!

-------- Sean Rieger 17:46 Sun 21 Nov      --------

**Comment by seanrieger** [comment]
@ahlstromcj Thank you. I managed to get it compiled and it's now running in a Eurorack Module (Raspberry Pi Based) I'm excited to get this to sync to an incoming MIDI clock, and it will be the central brain to my Modular Synth.

**Comment by mxmilkiib** [comment]
An aside regarding Linux and modular; JACK and LV2 can do 'CV', something you might find interesting, though atm, as far as my very vague understanding goes, the DC coupled DAC hat has a order waiting list.

More on https://linuxmusicians.com/viewtopic.php?f=1&t=20701

**Comment by seanrieger** [comment]
> 

@mxmilkiib Thanks so much. I've been fortunate to get that running as I have a DAV in the Terminal Tedium Module (Eurorack DAC for Raspberry Pi) I was just wondering, is Seq66 able to be a slave to an external midi clock? I'm trying to figure out how to do it, so when I hit play on my Keystep, the midi clock starts Seq66 in sync.
