### ISSUE TITLE
MIDI output bus assignments not saved with project

### ISSUE THREAD

**Issue by slightlynasty** [ahlstromcj/seq66#74]
Heya,

At some point midi output bus assignments for patterns stopped saving for me, so every time a project is opened all of the patterns are just routed to the first MIDI port in the list. MIDI channels are preserved though.

I get the same problem with both native JACK MIDI and ALSA.

(Also a bonus minor issue - disabling record mode for a pattern seems to kill the MIDI thru until the MIDI thru button is clicked on and off again)

**Comment by ahlstromcj** [comment]
I duplicated the first issue and fixed it.  A stupid bug (that I thought I had
already fixed) in converting "-1" to an integer.  It caused the 'usr' file
setting "buss-override" to be 0.  Doh!  I will be pushing out 0.98.2 later
today.

I cannot duplicate the thru bug, at least when clicking record in the pattern
editor.  What steps cause it for you?  Thanks!

-------- slightlynasty 01:43 Sat 01 Jan      --------

**Comment by slightlynasty** [comment]
Thanks, you know what? now I can't reproduce the bug either!

It was definitely doing it in some previous sessions, so I'm not sure if there's some very specific trigger at play. I'll keep an eye out for if it happens again.
