### ISSUE TITLE
NSM: starts always with a blank pattern

### ISSUE THREAD

**Issue by zaip** [ahlstromcj/seq66#79]
Hello!

I'm facing a problem after updating seq66 to 0.98.4 on a raspberry pi 4. When using NSM or RaySession the application always start with a blank midi file. The midifile newtune.midi.midi is saved when you save your work or close the session manager, but when you reopen the session a blank midi file is showed. If you inspect the midi file saved previously you'll see that the saved data is there.

I've uninstalled and installed seq66 several times and even did it on a fresh new install of ubuntu 21.10 for raspberry pi and the bug still happens. I also tried to change branch to portfix (0.98.5) and the behaviour is the same.

Any tips on this matter?

**Comment by ahlstromcj** [comment]
Well, first try setting load-most-recent to true, either in the 'rc' file's
"[recent-files]" section (after shutting down Seq66) or in Edit / Preferences /
Display / UI Boolean Options / Load Most Recent File at Startup.   (In the
latter case you can then go to the Session tab in the main windows and click
the "Reload Session" button.)

In the meantime I will test it under session management and look at another odd
issue I found!

-------- Alex Piaz 06:41 Sun 27 Feb      --------

>I'm facing a problem after updating seq66 to 0.98.4 on a raspberry pi 4. When
>using NSM or RaySession the application always start with a blank midi file.
>The midifile newtune.midi.midi is saved when you save your work or close the
>session manager, but when you reopen the session a blank midi file is showed.
>If you inspect the midi file saved previously you'll see that the saved data
>is there.  Any tips on this matter?

**Comment by zaip** [comment]
Hi

Thanks for answering so quickly! Your tip works fine!

The work you do in seq66 is so amazing and fast that we need to keep reading the manual because of the changes. I was not aware of that option.

Thanks again!

**Comment by mxmilkiib** [comment]
Not opening the previously saved MIDI file on start goes against the API https://new-session-manager.jackaudio.org/api/index.html#server-to-client-control-messages-open

**Comment by ahlstromcj** [comment]
Not sure I agree.  That talks about a "project".  The default for a project is
to open the last MIDI file, if it was saved.  If the user changes that, that is
the user's desires.

I will go through that section bit by bit to make sure the other provisos are
followed as will.  Thanks!

-------- Milkii Brewster 10:59 Sun 27 Feb      --------

>Not opening the previously saved MIDI file on start goes against the API https://new-session-manager.jackaudio.org/api/index.html#server-to-client-control-messages-open

**Comment by ahlstromcj** [comment]
I did find a frontal lobe eructation that disabled the load-most-recent setting. Doh!  And now renamed Quit to Hide.  Won't be in the portfix branch until tonight.  Will likely make a new release next weekend.
