### ISSUE TITLE
NSM support?

### ISSUE THREAD

**Issue by mxmilkiib** [ahlstromcj/seq66#8]
Similar to https://github.com/ahlstromcj/sequencer64/issues/1 but now there is an NSM fork, https://github.com/linuxaudio/new-session-manager

**Comment by ahlstromcj** [comment]
Check out master 0.91.1.  The author of RaySession has been rooting out issues with the NSM support.

**Comment by ahlstromcj** [comment]
Now in general bug fixing phase in nsm branch for upcoming 0.91.2.
