### ISSUE TITLE
Launchpad MIDI on input bus

### ISSUE THREAD

**Issue by slightlynasty** [ahlstromcj/seq66#80]
Not sure if I'm missing something here, but in order to use my Launchpad Mini with Seq66, it needs to be both checked in the "Input Buses" list and selected in the "MIDI Control Input", which works fine except that it means that the MIDI messages from the Launchpad also end up getting recorded into any loop that I try to record.

Particularly arming/disarming loops via the Launchpad in "record" mode has a tendency to write an unwanted note into the loop.

Cheers!

**Comment by ahlstromcj** [comment]
Thanks, I will look into it shortly.  Just seeing this now, because of so much
spam from AT&T, Nintendo, the FSF, soccer and bike stores, blah blah blah!
Overwhelms my phone, I have to use mutt to clear it all out.

-------- slightlynasty 01:57 Mon 18 Apr      --------

>Not sure if I'm missing something here, but in order to use my Launchpad Mini with Seq66, it needs to be both checked in the "Input Buses" list and selected in the "MIDI Control Input", which works fine except that it means that the MIDI messages from the Launchpad also end up getting recorded into any loop that I try to record.
>
>Particularly arming/disarming loops via the Launchpad in "record" mode has a tendency to write an unwanted note into the loop.

**Comment by ahlstromcj** [comment]
Hmmm, I had fixed this in version 0.98.7, but never recorded it in git log.  Will verify the fix for version 0.99.0 and then close this one.
