### ISSUE TITLE
Tabs don't scale to window

### ISSUE THREAD

**Issue by mxmilkiib** [ahlstromcj/seq66#82]
Playlist, Sets, Mutes and Session tabs don't scale to the main window size.

![image](https://user-images.githubusercontent.com/108225/165938187-e963a799-a64e-440d-8932-3ca0c8d67f7d.png)
etc.

**Comment by ahlstromcj** [comment]
Fixed for the main window, pattern editor, and song editor.  Am finding it impossible to get the Events, Playlist, Sets, Mutes, and Session tabs to expand vertically; have not yet looked a horizontally for those. Weird behavior when trying to apply layouts to the whole frame in the tabs.

Will push off to version 2, and make those external QDialogs, I think.

Tired of wrestling with this one. Only the frames with the grid or scrollmaster behave well.

**Comment by ahlstromcj** [comment]
Might consider moving those tabs into Edit / Preferences.
