### ISSUE TITLE
Increasing Rows and Cols causes a segmentation fault

### ISSUE THREAD

**Issue by AndrewPy** [ahlstromcj/seq66#87]
Increasing the UI Rows and Cols values (i.e. greater than 4x8) causes a segmentation fault on the next reboot.

In the settings UI itself, the value for the columns cannot be changed at all, it always switches back to the previous value when you leave the input field. It can only be changed by editing qseq66.usr.

(qseq66 0.98.9.1, Ubuntu 20.04.4 LTS, Qt v. 5.12.8)

**Comment by ahlstromcj** [comment]
I've found one source of the issue... the size of a mutegroup being restrictred to 32 patterns.  I will try to make that more flexible, but it will take awhile to track it all down properly.  Thanks for the report!

**Comment by ahlstromcj** [comment]
I have fixed this issue (and found other bugs via this one); no segfault, and editing in Edit / Preferences works.  Currently this fix is ONLY in the "portfix" branch.  I need to test some (including in WIndows) before I make it official in version 0.98.10.  Anyway, you can give it a build and try if you like.  The largest grid size you can get is 12x12, but I gotta work on scaling the font and the text positioning on the buttons.

**Comment by AndrewPy** [comment]
I've tried the portfix branch and it works great (for example 5x8).
Thank you very much!
