### ISSUE TITLE
seq66 does not recognize some changes for the save entry in the file menu

### ISSUE THREAD

**Issue by AndrewPy** [ahlstromcj/seq66#90]
For example: If you change the velocity of some notes or change the set name, the save entry in the menu remains disabled. You must use the save-as entry.

**Comment by ahlstromcj** [comment]
Thanks!  Add any other "modify not working" issues to this ticket as you come
across them.  I have had that one my to-do list, but this will make me get to
that task a lot faster.

>For example: If you change the velocity of some notes or change the set name, the save entry in the menu remains disabled. You must use the save-as entry.

**Comment by ahlstromcj** [comment]
I have basically fixed this issue.  However, the live grid slots flicker as one moves the mouse to change velocity or moves the sliders in the LFO box.  Both required the pattern editor to update, but not sure why the slots  (all of them!) get updated.  So some more probling to do.  But see the latest portfix branch.

**Comment by AndrewPy** [comment]
Again, I don't know if this comment isn't for the wrong issue(?).

In any case, there is a difference between the active state of the save menu item and the save prompt when the program is closed. (I think they should be treated largely identically.)

**Comment by ahlstromcj** [comment]
Still working on this one, now trying to get the Song Editor to show the modified status.  Wotta pain!  :-D

**Comment by ahlstromcj** [comment]
I'm closing this.  The current undo/redo/modify mechanism has been improved, but it cannot work completely.  In a potential version 2, I am working on a more air-tight history mechanism based on the Memento/History patterns from Gamma et al.  There won't be a Seq66v2 until I get a complete library that solves all the things that bug me about Seq66.  And I might well croak or become senescent before that happens! :-D
