### ISSUE TITLE
No colors in live view with xfce/xubuntu

### ISSUE THREAD

**Issue by AndrewPy** [ahlstromcj/seq66#91]
On xubuntu 20.04, the colors are not displayed in live view (but are visible in song view). qt5ct is installed.

**Comment by ahlstromcj** [comment]
Take a look at isuue #78.  There, setting the pattern-box sizes to 0 would
disable showing the pattern box at all.  I got rid of that mis-feature and
added a Shown check-box and shown option in the 'usr' file.  If the Shown box
is not checked (i.e. [user-ui-tweak] progress-box-shown = false), then the
progress boxes are disabled.  Maybe I should also disabled the coloring in the
Song view in that case?

>On xubuntu 20.04, the colors are not displayed in live view (but are visible in song view). qt5ct is installed.

**Comment by AndrewPy** [comment]
Sorry, i have overlooked issue #78.

So i created a bash script for setting the locales to "en_US.UTF-8" before starting qseq66 and the colors are working now. Thank you!

**Comment by ahlstromcj** [comment]
See the --help for the --locale option.

**Comment by AndrewPy** [comment]
Thank you, this works now (if the "Shown box" is enabled)!

**Comment by ahlstromcj** [comment]
Cool.  Can you paste the script in here?  Bjarne Stroustrup's C++11 book goes
at great lengths about locales and facets, and it should be possible to have
seq66 enforce that locale.  (As an option?)

>So i created a bash script for setting the locales to "en_US.UTF-8" before starting qseq66 and the colors are working now. Thank you!
