### ISSUE TITLE
Segfault when recording to a 32 beat pattern

### ISSUE THREAD

**Issue by AndrewPy** [ahlstromcj/seq66#92]
Sometimes there is a segfault when I record into a 32 beat pattern. Maybe it's due to the midi input settings (e.g. if more than one midi input port is selected?), but I couldn't clearly reproduce it, sorry. Sometimes it works well even taking hundreds of notes.

**Comment by ahlstromcj** [comment]
I had a similar seqfault issue at some point, also hard to reproduce. I think
it was issue #85.  Also see a similar note in Changelog for 2021-02-16.  Will
follow up on those.

>Sometimes there is a segfault when I record into a 32 beat pattern. Maybe it's due to the midi input settings (e.g. if more than one midi input port is selected?), but I couldn't clearly reproduce it, sorry. Sometimes it works well even taking hundreds of notes.

**Comment by ahlstromcj** [comment]
Will close this segfault issue for now.  Reopen or make a new issue if it recurs!
