### ISSUE TITLE
The window of a deleted pattern remains open

### ISSUE THREAD

**Issue by AndrewPy** [ahlstromcj/seq66#93]
If you delete a pattern from live view, the associated window remains open. You can even edit it, but it will be lost after closing.

**Comment by ahlstromcj** [comment]
Hmmm, I had thought I had disabled Delete/Cut from the menu.  But it sounds
better to remove the window as well.  Will think a bit before I act here.

>If you delete a pattern from live view, the associated window remains open. You can even edit it, but it will be lost after closing.

**Comment by AndrewPy** [comment]
Thanks, the deleted pattern window closes now. 

Unfortunately I discovered a similar problem with the "new pattern" function. Again, the old pattern content remains in an open window and can still be edited. But all (new) changes are lost if the window is closed afterwards.

**Comment by ahlstromcj** [comment]
Closing this.  Reopen or create a new issue if it recurs.
