### ISSUE TITLE
Long song cannot be scrolled to the right

### ISSUE THREAD

**Issue by AndrewPy** [ahlstromcj/seq66#94]
When creating a (very) long song, sometimes you can't scroll further to the right at the end of the song.

**Comment by ahlstromcj** [comment]
Thanks, will check it out.  I've seen that before.

>When creating a (very) long song, sometimes you can't scroll further to the right at the end of the song.

**Comment by AndrewPy** [comment]
Additional info for this issue:

When I have a song with 60 bars (in song view) und add 5 more patterns to one track, then i cannot add more, because i cannot scroll further. 
Resizing the Window helps (after that there is more room to scroll further).

**Comment by AndrewPy** [comment]
Thanks, the expand-grid button works perfect!
