### ISSUE TITLE
Feature Requests :)

### ISSUE THREAD

**Issue by score100** [ahlstromcj/seq66#98]
Hey, 
if you see any possibilites for the future I'd love this minor additions:
- Metronome
- Being able to record notes with a count-in before
- While in the piano-roll being able to start the pattern from the red cursor. For very detailed pattern editing :)

**Comment by ahlstromcj** [comment]
For the metronome you can allocate a pattern for that purpose.  But perhaps
you're looking for a system/computer beep to serve as a metronome (which would
be distinguishable from any MIDI device output)?

The count-in sounds like a reasonable feature, especially if you're gearing up
to record a long loop.

Actually, in the pattern editor you can set the "L" or "R" markers in the
"time" bar.  Then click the "L/R" button in the main window (I need to add that
button to the pattern editor as well).  And the progress bar will cycle between
L and R.

Without that L/R button on, play will start at L and continue.

Let me know if you have further suggestions about that feature after you have
toyed with it for a bit.  Thanks!

**Comment by score100** [comment]
`For the metronome you can allocate a pattern for that purpose.  But perhaps
you're looking for a system/computer beep to serve as a metronome (which would
be distinguishable from any MIDI device output)?`
Yes, the point is not having to create a pattern, draw the notes in, assign and use up a midi channel, firing up a host that can play back the click without having to configure that much.... Just one button and a sound being created :)

`The count-in sounds like a reasonable feature, especially if you're gearing up
to record a long loop.`
Great to hear that :)

`Actually, in the pattern editor you can set the "L" or "R" markers in the
"time" bar.  Then click the "L/R" button in the main window (I need to add that
button to the pattern editor as well).  And the progress bar will cycle between
L and R.`
Thanks, I'm aware of that feature. Maybe it helps to say that I got this idea from trackers I used in the past where you can indeed do both (play from current position and set looping area). I really prefer working with the keyboard over mouse and it feels more immediate when you're working on a detail of a pattern to just have one key. 
But maybe having the L and R markers linked to hotkeys could help for now.

**Comment by ahlstromcj** [comment]
There are hot-keys for the Time bar, but only in the Song Editor.  I somehow
forget to add them to the Time bar in the Pattern Editor :-D :-(

However, it's a bit clumsy at present.  In the Song Editor Time bar:

1. Click on "L" to give the Time bar keyboard focus without moving the "L".
2. Then press one of these keys (but in lower case):
    a. 'L' to prepare to move the "L" marker.
    b. 'R' to prepare to move the "R" marker.
3. Use the Left or Right arrow keys to move the selected marker.

If you come up with a better idea about how to do this, let me know!

Also, in both Song and Pattern editor piano rolls, you can hit
Space to start/stop, "." to pause/continue, and "Esc" to stop.

My motto:

-- 
You are only young once, but you can stay immature indefinitely.

**Comment by ahlstromcj** [comment]
Closing this as done.  Any new issues, create it!
